// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_scrBoot.h"
#include "screens/ui_scrPlotter.h"
#include "screens/ui_scrFFT.h"
#include "screens/ui_scrMenu.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_icons_icon_plotter_chart_png);   // assets/icons/icon_plotter_chart.png
LV_IMG_DECLARE( ui_img_icons_icon_fft_chart_png);   // assets/icons/icon_fft_chart.png

// FONTS
LV_FONT_DECLARE( ui_font_poppinsBold10);
LV_FONT_DECLARE( ui_font_poppinsReg10);
LV_FONT_DECLARE( ui_font_poppinsReg8);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
