// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "../ui.h"

lv_obj_t *ui_scrMenu = NULL;lv_obj_t *ui_scrMenu_contTopBar = NULL;lv_obj_t *ui_scrMenu_btnMenuPlotter = NULL;lv_obj_t *ui_scrMenu_btnMenuFFT = NULL;
// event funtions
void ui_event_scrMenu( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_scrPlotter, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_scrPlotter_screen_init);
}
}

void ui_event_scrMenu_btnMenuFFT( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_scrFFT, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_scrFFT_screen_init);
}
}

// build funtions

void ui_scrMenu_screen_init(void)
{
ui_scrMenu = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrMenu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrMenu_contTopBar = ui_contTopBar_create(ui_scrMenu);
lv_obj_set_x( ui_scrMenu_contTopBar, 0 );
lv_obj_set_y( ui_scrMenu_contTopBar, 0 );

ui_scrMenu_btnMenuPlotter = lv_button_create(ui_scrMenu);
lv_obj_set_width( ui_scrMenu_btnMenuPlotter, 80);
lv_obj_set_height( ui_scrMenu_btnMenuPlotter, 80);
lv_obj_set_x( ui_scrMenu_btnMenuPlotter, 20 );
lv_obj_set_y( ui_scrMenu_btnMenuPlotter, 40 );
lv_obj_add_flag( ui_scrMenu_btnMenuPlotter, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrMenu_btnMenuPlotter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrMenu_btnMenuPlotter, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrMenu_btnMenuPlotter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrMenu_btnMenuPlotter, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_scrMenu_btnMenuPlotter, &ui_img_icons_icon_plotter_chart_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_scrMenu_btnMenuPlotter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_scrMenu_btnMenuPlotter, 25, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_scrMenu_btnMenuFFT = lv_button_create(ui_scrMenu);
lv_obj_set_width( ui_scrMenu_btnMenuFFT, 80);
lv_obj_set_height( ui_scrMenu_btnMenuFFT, 80);
lv_obj_set_x( ui_scrMenu_btnMenuFFT, 120 );
lv_obj_set_y( ui_scrMenu_btnMenuFFT, 40 );
lv_obj_add_flag( ui_scrMenu_btnMenuFFT, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrMenu_btnMenuFFT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrMenu_btnMenuFFT, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrMenu_btnMenuFFT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrMenu_btnMenuFFT, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_scrMenu_btnMenuFFT, &ui_img_icons_icon_fft_chart_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_scrMenu_btnMenuFFT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_scrMenu_btnMenuFFT, 25, LV_PART_MAIN| LV_STATE_FOCUSED);

lv_obj_add_event_cb(ui_scrMenu_btnMenuFFT, ui_event_scrMenu_btnMenuFFT, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_scrMenu, ui_event_scrMenu, LV_EVENT_ALL, NULL);

}

void ui_scrMenu_screen_destroy(void)
{
   if (ui_scrMenu) lv_obj_del(ui_scrMenu);

// NULL screen variables
ui_scrMenu= NULL;
ui_scrMenu_contTopBar= NULL;
ui_scrMenu_btnMenuPlotter= NULL;
ui_scrMenu_btnMenuFFT= NULL;

}
