// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "../ui.h"

lv_obj_t *ui_scrFFT = NULL;lv_obj_t *ui_scrFFT_contTopBar = NULL;lv_obj_t *ui_scrFFT_chartFFT = NULL;lv_obj_t *ui_scrFFT_chartFFT_Xaxis = NULL;lv_obj_t *ui_scrFFT_chartFFT_Yaxis1 = NULL;lv_obj_t *ui_scrFFT_chartFFT_Yaxis2 = NULL;
// event funtions

// build funtions

void ui_scrFFT_screen_init(void)
{
ui_scrFFT = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrFFT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_scrFFT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrFFT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrFFT_contTopBar = ui_contTopBar_create(ui_scrFFT);
lv_obj_set_x( ui_scrFFT_contTopBar, 0 );
lv_obj_set_y( ui_scrFFT_contTopBar, 0 );

ui_scrFFT_chartFFT = lv_chart_create(ui_scrFFT);
lv_obj_set_width( ui_scrFFT_chartFFT, 420);
lv_obj_set_height( ui_scrFFT_chartFFT, 265);
lv_obj_set_x( ui_scrFFT_chartFFT, 50 );
lv_obj_set_y( ui_scrFFT_chartFFT, 30 );
lv_obj_add_flag( ui_scrFFT_chartFFT, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_scrFFT_chartFFT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_scrFFT_chartFFT, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_scrFFT_chartFFT, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_scrFFT_chartFFT, LV_CHART_TYPE_LINE);
lv_chart_set_axis_range( ui_scrFFT_chartFFT, LV_CHART_AXIS_PRIMARY_Y, 0, 250);
lv_chart_set_axis_range( ui_scrFFT_chartFFT, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
lv_obj_set_style_radius(ui_scrFFT_chartFFT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrFFT_chartFFT, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrFFT_chartFFT, 79, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_scrFFT_chartFFT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrFFT_chartFFT_Xaxis = lv_scale_create( ui_scrFFT_chartFFT );
lv_scale_set_mode( ui_scrFFT_chartFFT_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_scrFFT_chartFFT_Xaxis, lv_pct(100), 10 );
lv_obj_set_align( ui_scrFFT_chartFFT_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_scrFFT_chartFFT_Xaxis, 10 + lv_obj_get_style_pad_bottom(ui_scrFFT_chartFFT,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_scrFFT_chartFFT,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_scrFFT_chartFFT_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_scrFFT_chartFFT_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_scrFFT_chartFFT_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_scrFFT_chartFFT_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_scrFFT_chartFFT_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_scrFFT_chartFFT_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_scrFFT_chartFFT_Xaxis, (5>0 ? 5-1 : 0) * 5 + 1 );
lv_scale_set_major_tick_every( ui_scrFFT_chartFFT_Xaxis, 5 >= 1 ? 5 : 1 );
ui_scrFFT_chartFFT_Yaxis1 = lv_scale_create( ui_scrFFT_chartFFT );
lv_scale_set_mode( ui_scrFFT_chartFFT_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_scrFFT_chartFFT_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_scrFFT_chartFFT_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_scrFFT_chartFFT_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_scrFFT_chartFFT,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_scrFFT_chartFFT,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_scrFFT_chartFFT_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_scrFFT_chartFFT_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_scrFFT_chartFFT_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_scrFFT_chartFFT_Yaxis1, 0, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_scrFFT_chartFFT_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_range( ui_scrFFT_chartFFT_Yaxis1,  0, 250 );
lv_scale_set_total_tick_count( ui_scrFFT_chartFFT_Yaxis1, (3 > 0 ? 3-1 : 0) * 1 + 1 );
lv_scale_set_major_tick_every( ui_scrFFT_chartFFT_Yaxis1, 1 >= 1 ? 1 : 1 );
ui_scrFFT_chartFFT_Yaxis2 = lv_scale_create( ui_scrFFT_chartFFT );
lv_scale_set_mode( ui_scrFFT_chartFFT_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_align( ui_scrFFT_chartFFT_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_style_line_width( ui_scrFFT_chartFFT_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_scrFFT_chartFFT_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_scrFFT_chartFFT_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_scrFFT_chartFFT_Yaxis2, 0, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_scrFFT_chartFFT_Yaxis2, 0, LV_PART_INDICATOR ); //major tick length
lv_scale_set_range( ui_scrFFT_chartFFT_Yaxis2,  0, 0 );
lv_scale_set_total_tick_count( ui_scrFFT_chartFFT_Yaxis2, (0 > 0 ? 0-1 : 0) * 0 + 1 );
lv_scale_set_major_tick_every( ui_scrFFT_chartFFT_Yaxis2, 0 >= 1 ? 0 : 1 );
lv_scale_set_label_show( ui_scrFFT_chartFFT_Yaxis2, false );

lv_obj_set_style_size(ui_scrFFT_chartFFT, 0, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_scrFFT_chartFFT, LV_MAX3(10, 50, 0), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_scrFFT_chartFFT, -1, LV_PART_MAIN | LV_STATE_DEFAULT );

}

void ui_scrFFT_screen_destroy(void)
{
   if (ui_scrFFT) lv_obj_del(ui_scrFFT);

// NULL screen variables
ui_scrFFT= NULL;
ui_scrFFT_contTopBar= NULL;
ui_scrFFT_chartFFT= NULL;

}
