// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRSETTINGS_H
#define UI_SCRSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrSettings
extern void ui_scrSettings_screen_init(void);
extern void ui_scrSettings_screen_destroy(void);
extern lv_obj_t *ui_scrSettings;
extern lv_obj_t *ui_scrSettings_contTopBar2;
extern lv_obj_t *ui_scrSettings_lblSettings;
extern void ui_event_scrSettings_btnBack( lv_event_t * e);
extern lv_obj_t *ui_scrSettings_btnBack;
extern void ui_event_scrSettings_cntDatetime( lv_event_t * e);
extern lv_obj_t *ui_scrSettings_cntDatetime;
extern lv_obj_t *ui_scrSettings_iconDatetime;
extern lv_obj_t *ui_scrSettings_lblDatetime;
extern lv_obj_t *ui_scrSettings_lblDatetimeBrief;
extern lv_obj_t *ui_scrSettings_iconDatetimeEnter;
extern lv_obj_t *ui_scrSettings_cntScreen;
extern lv_obj_t *ui_scrSettings_iconScreen;
extern lv_obj_t *ui_scrSettings_lblScreen;
extern lv_obj_t *ui_scrSettings_lblScreenBrief;
extern lv_obj_t *ui_scrSettings_iconScreenEnter;
extern lv_obj_t *ui_scrSettings_cntMeasure;
extern lv_obj_t *ui_scrSettings_iconMeasure;
extern lv_obj_t *ui_scrSettings_lblMeasure;
extern lv_obj_t *ui_scrSettings_lblMeasureBrief;
extern lv_obj_t *ui_scrSettings_iconMeasureEnter;
extern lv_obj_t *ui_scrSettings_cntInfo;
extern lv_obj_t *ui_scrSettings_iconInfo;
extern lv_obj_t *ui_scrSettings_lblInfo;
extern lv_obj_t *ui_scrSettings_lblInfoBrief;
extern lv_obj_t *ui_scrSettings_iconInfoEnter;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

