// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "../ui.h"

lv_obj_t *ui_scrInformation = NULL;lv_obj_t *ui_scrInformation_contTopBar = NULL;lv_obj_t *ui_scrInformation_lblInfo = NULL;lv_obj_t *ui_scrInformation_btnBack = NULL;lv_obj_t *ui_scrInformation_cntDevice = NULL;lv_obj_t *ui_scrInformation_logo = NULL;lv_obj_t *ui_scrInformation_lblName = NULL;lv_obj_t *ui_scrInformation_lblSubname = NULL;lv_obj_t *ui_scrInformation_cntModel = NULL;lv_obj_t *ui_scrInformation_lblModel = NULL;lv_obj_t *ui_scrInformation_lblModelV = NULL;lv_obj_t *ui_scrInformation_cntSerial = NULL;lv_obj_t *ui_scrInformation_lblSerial = NULL;lv_obj_t *ui_scrInformation_lblSerialV = NULL;lv_obj_t *ui_scrInformation_cntFirmware = NULL;lv_obj_t *ui_scrInformation_lblFirmware = NULL;lv_obj_t *ui_scrInformation_lblFirmwareV = NULL;lv_obj_t *ui_scrInformation_cntBuild = NULL;lv_obj_t *ui_scrInformation_lblBuild = NULL;lv_obj_t *ui_scrInformation_lblBuildV = NULL;lv_obj_t *ui_scrInformation_cntHardware = NULL;lv_obj_t *ui_scrInformation_lblHardware = NULL;lv_obj_t *ui_scrInformation_cntMcu = NULL;lv_obj_t *ui_scrInformation_lblMcu = NULL;lv_obj_t *ui_scrInformation_lblMcuV = NULL;lv_obj_t *ui_scrInformation_cntAdc = NULL;lv_obj_t *ui_scrInformation_lblAdc = NULL;lv_obj_t *ui_scrInformation_lblAdcV = NULL;lv_obj_t *ui_scrInformation_cntActiveTime = NULL;lv_obj_t *ui_scrInformation_lblActiveTime = NULL;lv_obj_t *ui_scrInformation_lblActiveTimeV = NULL;lv_obj_t *ui_scrInformation_cntBy = NULL;lv_obj_t *ui_scrInformation_lblBy = NULL;lv_obj_t *ui_scrInformation_lblUniversity = NULL;lv_obj_t *ui_scrInformation_lblProject = NULL;
// event funtions
void ui_event_scrInformation_btnBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_scrSettings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_scrSettings_screen_init);
}
}

// build funtions

void ui_scrInformation_screen_init(void)
{
ui_scrInformation = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrInformation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrInformation, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrInformation, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);

ui_scrInformation_contTopBar = ui_contTopBar_create(ui_scrInformation);
lv_obj_set_x( ui_scrInformation_contTopBar, 0 );
lv_obj_set_y( ui_scrInformation_contTopBar, 0 );

ui_scrInformation_lblInfo = lv_label_create(ui_scrInformation);
lv_obj_set_width( ui_scrInformation_lblInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblInfo, 52 );
lv_obj_set_y( ui_scrInformation_lblInfo, 41 );
lv_label_set_text(ui_scrInformation_lblInfo,"Información");
ui_object_set_themeable_style_property(ui_scrInformation_lblInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrInformation_lblInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrInformation_lblInfo, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrInformation_lblInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrInformation_lblInfo, &ui_font_SansBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_btnBack = lv_image_create(ui_scrInformation);
lv_image_set_src(ui_scrInformation_btnBack, &ui_img_icons_ic_back_png);
lv_obj_set_width( ui_scrInformation_btnBack, 28);
lv_obj_set_height( ui_scrInformation_btnBack, 28);
lv_obj_set_x( ui_scrInformation_btnBack, 14 );
lv_obj_set_y( ui_scrInformation_btnBack, 37 );
lv_obj_add_flag( ui_scrInformation_btnBack, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrInformation_btnBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrInformation_btnBack,85);
lv_obj_set_style_radius(ui_scrInformation_btnBack, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Card);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Card);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrInformation_btnBack, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrInformation_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrInformation_cntDevice = lv_obj_create(ui_scrInformation);
lv_obj_remove_style_all(ui_scrInformation_cntDevice);
lv_obj_set_width( ui_scrInformation_cntDevice, 235);
lv_obj_set_height( ui_scrInformation_cntDevice, 238);
lv_obj_set_x( ui_scrInformation_cntDevice, 14 );
lv_obj_set_y( ui_scrInformation_cntDevice, 70 );
lv_obj_remove_flag( ui_scrInformation_cntDevice, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrInformation_cntDevice, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrInformation_cntDevice, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Card);
ui_object_set_themeable_style_property(ui_scrInformation_cntDevice, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Card);
ui_object_set_themeable_style_property(ui_scrInformation_cntDevice, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrInformation_cntDevice, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrInformation_cntDevice, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_logo = lv_image_create(ui_scrInformation_cntDevice);
lv_image_set_src(ui_scrInformation_logo, &ui_img_1310808144);
lv_obj_set_width( ui_scrInformation_logo, 38);
lv_obj_set_height( ui_scrInformation_logo, 38);
lv_obj_set_x( ui_scrInformation_logo, 15 );
lv_obj_set_y( ui_scrInformation_logo, 13 );
lv_obj_add_flag( ui_scrInformation_logo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrInformation_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrInformation_logo,112);

ui_scrInformation_lblName = lv_label_create(ui_scrInformation_cntDevice);
lv_obj_set_width( ui_scrInformation_lblName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblName, 64 );
lv_obj_set_y( ui_scrInformation_lblName, 15 );
lv_label_set_text(ui_scrInformation_lblName,"Analizador Trifásico");
ui_object_set_themeable_style_property(ui_scrInformation_lblName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrInformation_lblName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_font(ui_scrInformation_lblName, &ui_font_SansBold15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblSubname = lv_label_create(ui_scrInformation_cntDevice);
lv_obj_set_width( ui_scrInformation_lblSubname, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblSubname, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblSubname, 64 );
lv_obj_set_y( ui_scrInformation_lblSubname, 36 );
lv_label_set_text(ui_scrInformation_lblSubname,"MODO MONOFÁSICO");
ui_object_set_themeable_style_property(ui_scrInformation_lblSubname, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrInformation_lblSubname, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_text_letter_space(ui_scrInformation_lblSubname, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrInformation_lblSubname, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrInformation_lblSubname, &ui_font_SansBold10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_cntModel = lv_obj_create(ui_scrInformation_cntDevice);
lv_obj_remove_style_all(ui_scrInformation_cntModel);
lv_obj_set_width( ui_scrInformation_cntModel, 205);
lv_obj_set_height( ui_scrInformation_cntModel, 16);
lv_obj_set_x( ui_scrInformation_cntModel, 15 );
lv_obj_set_y( ui_scrInformation_cntModel, 121 );
lv_obj_remove_flag( ui_scrInformation_cntModel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrInformation_cntModel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrInformation_cntModel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrInformation_cntModel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_scrInformation_cntModel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblModel = lv_label_create(ui_scrInformation_cntModel);
lv_obj_set_width( ui_scrInformation_lblModel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblModel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_scrInformation_lblModel,"Modelo");
ui_object_set_themeable_style_property(ui_scrInformation_lblModel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrInformation_lblModel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_font(ui_scrInformation_lblModel, &ui_font_SansMed10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblModelV = lv_label_create(ui_scrInformation_cntModel);
lv_obj_set_width( ui_scrInformation_lblModelV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblModelV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblModelV, 0 );
lv_obj_set_y( ui_scrInformation_lblModelV, -3 );
lv_obj_set_align( ui_scrInformation_lblModelV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_scrInformation_lblModelV,"ATRI-01");
ui_object_set_themeable_style_property(ui_scrInformation_lblModelV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrInformation_lblModelV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrInformation_lblModelV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrInformation_lblModelV, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrInformation_lblModelV, &ui_font_SansMed12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_cntSerial = lv_obj_create(ui_scrInformation_cntDevice);
lv_obj_remove_style_all(ui_scrInformation_cntSerial);
lv_obj_set_width( ui_scrInformation_cntSerial, 205);
lv_obj_set_height( ui_scrInformation_cntSerial, 16);
lv_obj_set_x( ui_scrInformation_cntSerial, 15 );
lv_obj_set_y( ui_scrInformation_cntSerial, 146 );
lv_obj_remove_flag( ui_scrInformation_cntSerial, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrInformation_cntSerial, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrInformation_cntSerial, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrInformation_cntSerial, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_scrInformation_cntSerial, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblSerial = lv_label_create(ui_scrInformation_cntSerial);
lv_obj_set_width( ui_scrInformation_lblSerial, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblSerial, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_scrInformation_lblSerial,"Nro de Serie");
ui_object_set_themeable_style_property(ui_scrInformation_lblSerial, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrInformation_lblSerial, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_font(ui_scrInformation_lblSerial, &ui_font_SansMed10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblSerialV = lv_label_create(ui_scrInformation_cntSerial);
lv_obj_set_width( ui_scrInformation_lblSerialV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblSerialV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblSerialV, 0 );
lv_obj_set_y( ui_scrInformation_lblSerialV, -3 );
lv_obj_set_align( ui_scrInformation_lblSerialV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_scrInformation_lblSerialV,"ATRI-0001");
ui_object_set_themeable_style_property(ui_scrInformation_lblSerialV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrInformation_lblSerialV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrInformation_lblSerialV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrInformation_lblSerialV, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrInformation_lblSerialV, &ui_font_SansMed12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_cntFirmware = lv_obj_create(ui_scrInformation_cntDevice);
lv_obj_remove_style_all(ui_scrInformation_cntFirmware);
lv_obj_set_width( ui_scrInformation_cntFirmware, 205);
lv_obj_set_height( ui_scrInformation_cntFirmware, 16);
lv_obj_set_x( ui_scrInformation_cntFirmware, 15 );
lv_obj_set_y( ui_scrInformation_cntFirmware, 171 );
lv_obj_remove_flag( ui_scrInformation_cntFirmware, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrInformation_cntFirmware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrInformation_cntFirmware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrInformation_cntFirmware, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_scrInformation_cntFirmware, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblFirmware = lv_label_create(ui_scrInformation_cntFirmware);
lv_obj_set_width( ui_scrInformation_lblFirmware, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblFirmware, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_scrInformation_lblFirmware,"Firmware");
ui_object_set_themeable_style_property(ui_scrInformation_lblFirmware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrInformation_lblFirmware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_font(ui_scrInformation_lblFirmware, &ui_font_SansMed10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblFirmwareV = lv_label_create(ui_scrInformation_cntFirmware);
lv_obj_set_width( ui_scrInformation_lblFirmwareV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblFirmwareV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblFirmwareV, 0 );
lv_obj_set_y( ui_scrInformation_lblFirmwareV, -3 );
lv_obj_set_align( ui_scrInformation_lblFirmwareV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_scrInformation_lblFirmwareV,"v0.1.0");
ui_object_set_themeable_style_property(ui_scrInformation_lblFirmwareV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrInformation_lblFirmwareV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrInformation_lblFirmwareV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrInformation_lblFirmwareV, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrInformation_lblFirmwareV, &ui_font_SansMed12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_cntBuild = lv_obj_create(ui_scrInformation_cntDevice);
lv_obj_remove_style_all(ui_scrInformation_cntBuild);
lv_obj_set_width( ui_scrInformation_cntBuild, 205);
lv_obj_set_height( ui_scrInformation_cntBuild, 16);
lv_obj_set_x( ui_scrInformation_cntBuild, 15 );
lv_obj_set_y( ui_scrInformation_cntBuild, 196 );
lv_obj_remove_flag( ui_scrInformation_cntBuild, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrInformation_cntBuild, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrInformation_cntBuild, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrInformation_cntBuild, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_scrInformation_cntBuild, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblBuild = lv_label_create(ui_scrInformation_cntBuild);
lv_obj_set_width( ui_scrInformation_lblBuild, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblBuild, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_scrInformation_lblBuild,"Compilación");
ui_object_set_themeable_style_property(ui_scrInformation_lblBuild, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrInformation_lblBuild, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_font(ui_scrInformation_lblBuild, &ui_font_SansMed10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblBuildV = lv_label_create(ui_scrInformation_cntBuild);
lv_obj_set_width( ui_scrInformation_lblBuildV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblBuildV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblBuildV, 0 );
lv_obj_set_y( ui_scrInformation_lblBuildV, -3 );
lv_obj_set_align( ui_scrInformation_lblBuildV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_scrInformation_lblBuildV,"20/06/2026");
ui_object_set_themeable_style_property(ui_scrInformation_lblBuildV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrInformation_lblBuildV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrInformation_lblBuildV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrInformation_lblBuildV, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrInformation_lblBuildV, &ui_font_SansMed12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_cntHardware = lv_obj_create(ui_scrInformation);
lv_obj_remove_style_all(ui_scrInformation_cntHardware);
lv_obj_set_width( ui_scrInformation_cntHardware, 205);
lv_obj_set_height( ui_scrInformation_cntHardware, 118);
lv_obj_set_x( ui_scrInformation_cntHardware, 261 );
lv_obj_set_y( ui_scrInformation_cntHardware, 70 );
lv_obj_remove_flag( ui_scrInformation_cntHardware, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrInformation_cntHardware, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrInformation_cntHardware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Card);
ui_object_set_themeable_style_property(ui_scrInformation_cntHardware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Card);
ui_object_set_themeable_style_property(ui_scrInformation_cntHardware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrInformation_cntHardware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrInformation_cntHardware, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblHardware = lv_label_create(ui_scrInformation_cntHardware);
lv_obj_set_width( ui_scrInformation_lblHardware, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblHardware, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblHardware, 15 );
lv_obj_set_y( ui_scrInformation_lblHardware, 10 );
lv_label_set_text(ui_scrInformation_lblHardware,"HARDWARE");
ui_object_set_themeable_style_property(ui_scrInformation_lblHardware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrInformation_lblHardware, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_letter_space(ui_scrInformation_lblHardware, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrInformation_lblHardware, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrInformation_lblHardware, &ui_font_SansBold10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_cntMcu = lv_obj_create(ui_scrInformation_cntHardware);
lv_obj_remove_style_all(ui_scrInformation_cntMcu);
lv_obj_set_width( ui_scrInformation_cntMcu, 175);
lv_obj_set_height( ui_scrInformation_cntMcu, 16);
lv_obj_set_x( ui_scrInformation_cntMcu, 15 );
lv_obj_set_y( ui_scrInformation_cntMcu, 37 );
lv_obj_remove_flag( ui_scrInformation_cntMcu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrInformation_cntMcu, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrInformation_cntMcu, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrInformation_cntMcu, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_scrInformation_cntMcu, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblMcu = lv_label_create(ui_scrInformation_cntMcu);
lv_obj_set_width( ui_scrInformation_lblMcu, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblMcu, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_scrInformation_lblMcu,"MCU");
ui_object_set_themeable_style_property(ui_scrInformation_lblMcu, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrInformation_lblMcu, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_font(ui_scrInformation_lblMcu, &ui_font_SansMed10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblMcuV = lv_label_create(ui_scrInformation_cntMcu);
lv_obj_set_width( ui_scrInformation_lblMcuV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblMcuV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblMcuV, 0 );
lv_obj_set_y( ui_scrInformation_lblMcuV, -3 );
lv_obj_set_align( ui_scrInformation_lblMcuV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_scrInformation_lblMcuV,"RP2350A");
ui_object_set_themeable_style_property(ui_scrInformation_lblMcuV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrInformation_lblMcuV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrInformation_lblMcuV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrInformation_lblMcuV, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrInformation_lblMcuV, &ui_font_SansMed12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_cntAdc = lv_obj_create(ui_scrInformation_cntHardware);
lv_obj_remove_style_all(ui_scrInformation_cntAdc);
lv_obj_set_width( ui_scrInformation_cntAdc, 175);
lv_obj_set_height( ui_scrInformation_cntAdc, 16);
lv_obj_set_x( ui_scrInformation_cntAdc, 15 );
lv_obj_set_y( ui_scrInformation_cntAdc, 62 );
lv_obj_remove_flag( ui_scrInformation_cntAdc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrInformation_cntAdc, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrInformation_cntAdc, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrInformation_cntAdc, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_scrInformation_cntAdc, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblAdc = lv_label_create(ui_scrInformation_cntAdc);
lv_obj_set_width( ui_scrInformation_lblAdc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblAdc, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_scrInformation_lblAdc,"ADC");
ui_object_set_themeable_style_property(ui_scrInformation_lblAdc, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrInformation_lblAdc, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_font(ui_scrInformation_lblAdc, &ui_font_SansMed10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblAdcV = lv_label_create(ui_scrInformation_cntAdc);
lv_obj_set_width( ui_scrInformation_lblAdcV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblAdcV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblAdcV, 0 );
lv_obj_set_y( ui_scrInformation_lblAdcV, -3 );
lv_obj_set_align( ui_scrInformation_lblAdcV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_scrInformation_lblAdcV,"12 bit - 500 kS/s");
ui_object_set_themeable_style_property(ui_scrInformation_lblAdcV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrInformation_lblAdcV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrInformation_lblAdcV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrInformation_lblAdcV, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrInformation_lblAdcV, &ui_font_SansMed12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_cntActiveTime = lv_obj_create(ui_scrInformation_cntHardware);
lv_obj_remove_style_all(ui_scrInformation_cntActiveTime);
lv_obj_set_width( ui_scrInformation_cntActiveTime, 175);
lv_obj_set_height( ui_scrInformation_cntActiveTime, 16);
lv_obj_set_x( ui_scrInformation_cntActiveTime, 15 );
lv_obj_set_y( ui_scrInformation_cntActiveTime, 87 );
lv_obj_remove_flag( ui_scrInformation_cntActiveTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrInformation_cntActiveTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrInformation_cntActiveTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrInformation_cntActiveTime, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_scrInformation_cntActiveTime, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblActiveTime = lv_label_create(ui_scrInformation_cntActiveTime);
lv_obj_set_width( ui_scrInformation_lblActiveTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblActiveTime, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_scrInformation_lblActiveTime,"Tiempo Activo");
ui_object_set_themeable_style_property(ui_scrInformation_lblActiveTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrInformation_lblActiveTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_font(ui_scrInformation_lblActiveTime, &ui_font_SansMed10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblActiveTimeV = lv_label_create(ui_scrInformation_cntActiveTime);
lv_obj_set_width( ui_scrInformation_lblActiveTimeV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblActiveTimeV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblActiveTimeV, 0 );
lv_obj_set_y( ui_scrInformation_lblActiveTimeV, -3 );
lv_obj_set_align( ui_scrInformation_lblActiveTimeV, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_scrInformation_lblActiveTimeV,"06:06:01");
ui_object_set_themeable_style_property(ui_scrInformation_lblActiveTimeV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrInformation_lblActiveTimeV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrInformation_lblActiveTimeV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrInformation_lblActiveTimeV, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrInformation_lblActiveTimeV, &ui_font_SansMed12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_cntBy = lv_obj_create(ui_scrInformation);
lv_obj_remove_style_all(ui_scrInformation_cntBy);
lv_obj_set_width( ui_scrInformation_cntBy, 205);
lv_obj_set_height( ui_scrInformation_cntBy, 110);
lv_obj_set_x( ui_scrInformation_cntBy, 261 );
lv_obj_set_y( ui_scrInformation_cntBy, 198 );
lv_obj_remove_flag( ui_scrInformation_cntBy, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrInformation_cntBy, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrInformation_cntBy, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrInformation_cntBy, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrInformation_cntBy, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrInformation_cntBy, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrInformation_cntBy, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblBy = lv_label_create(ui_scrInformation_cntBy);
lv_obj_set_width( ui_scrInformation_lblBy, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblBy, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblBy, 15 );
lv_obj_set_y( ui_scrInformation_lblBy, 14 );
lv_label_set_text(ui_scrInformation_lblBy,"DESARROLADO EN");
ui_object_set_themeable_style_property(ui_scrInformation_lblBy, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrInformation_lblBy, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_letter_space(ui_scrInformation_lblBy, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrInformation_lblBy, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrInformation_lblBy, &ui_font_SansBold10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblUniversity = lv_label_create(ui_scrInformation_cntBy);
lv_obj_set_width( ui_scrInformation_lblUniversity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblUniversity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblUniversity, 15 );
lv_obj_set_y( ui_scrInformation_lblUniversity, 30 );
lv_label_set_text(ui_scrInformation_lblUniversity,"UTN - Facultad Regional\nAvellaneda");
ui_object_set_themeable_style_property(ui_scrInformation_lblUniversity, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrInformation_lblUniversity, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_font(ui_scrInformation_lblUniversity, &ui_font_SansBold13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrInformation_lblProject = lv_label_create(ui_scrInformation_cntBy);
lv_obj_set_width( ui_scrInformation_lblProject, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrInformation_lblProject, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrInformation_lblProject, 15 );
lv_obj_set_y( ui_scrInformation_lblProject, 69 );
lv_label_set_text(ui_scrInformation_lblProject,"Proyecto Final de Ingeniería\nElectrónica");
ui_object_set_themeable_style_property(ui_scrInformation_lblProject, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrInformation_lblProject, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_font(ui_scrInformation_lblProject, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_scrInformation_btnBack, ui_event_scrInformation_btnBack, LV_EVENT_ALL, NULL);

}

void ui_scrInformation_screen_destroy(void)
{
   if (ui_scrInformation) lv_obj_del(ui_scrInformation);

// NULL screen variables
ui_scrInformation= NULL;
ui_scrInformation_contTopBar= NULL;
ui_scrInformation_lblInfo= NULL;
ui_scrInformation_btnBack= NULL;
ui_scrInformation_cntDevice= NULL;
ui_scrInformation_logo= NULL;
ui_scrInformation_lblName= NULL;
ui_scrInformation_lblSubname= NULL;
ui_scrInformation_cntModel= NULL;
ui_scrInformation_lblModel= NULL;
ui_scrInformation_lblModelV= NULL;
ui_scrInformation_cntSerial= NULL;
ui_scrInformation_lblSerial= NULL;
ui_scrInformation_lblSerialV= NULL;
ui_scrInformation_cntFirmware= NULL;
ui_scrInformation_lblFirmware= NULL;
ui_scrInformation_lblFirmwareV= NULL;
ui_scrInformation_cntBuild= NULL;
ui_scrInformation_lblBuild= NULL;
ui_scrInformation_lblBuildV= NULL;
ui_scrInformation_cntHardware= NULL;
ui_scrInformation_lblHardware= NULL;
ui_scrInformation_cntMcu= NULL;
ui_scrInformation_lblMcu= NULL;
ui_scrInformation_lblMcuV= NULL;
ui_scrInformation_cntAdc= NULL;
ui_scrInformation_lblAdc= NULL;
ui_scrInformation_lblAdcV= NULL;
ui_scrInformation_cntActiveTime= NULL;
ui_scrInformation_lblActiveTime= NULL;
ui_scrInformation_lblActiveTimeV= NULL;
ui_scrInformation_cntBy= NULL;
ui_scrInformation_lblBy= NULL;
ui_scrInformation_lblUniversity= NULL;
ui_scrInformation_lblProject= NULL;

}
