// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCROSCILLOSCOPE_H
#define UI_SCROSCILLOSCOPE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrOscilloscope
extern void ui_scrOscilloscope_screen_init(void);
extern void ui_scrOscilloscope_screen_destroy(void);
extern lv_obj_t *ui_scrOscilloscope;
extern lv_obj_t *ui_scrOscilloscope_contTopBar;
extern lv_obj_t *ui_scrOscilloscope_lblTitle;
extern lv_obj_t *ui_scrOscilloscope_cntTension;
extern lv_obj_t *ui_scrOscilloscope_legendVoltage;
extern lv_obj_t *ui_scrOscilloscope_lblTension;
extern lv_obj_t *ui_scrOscilloscope_cntCorriente;
extern lv_obj_t *ui_scrOscilloscope_legendCorriente;
extern lv_obj_t *ui_scrOscilloscope_lblCorriente;
extern lv_obj_t *ui_scrOscilloscope_cntValues;
extern lv_obj_t *ui_scrOscilloscope_cntPeak;
extern lv_obj_t *ui_scrOscilloscope_lblPeak;
extern lv_obj_t *ui_scrOscilloscope_lblPeakValue;
extern lv_obj_t *ui_scrOscilloscope_lblPeakUnit;
extern lv_obj_t *ui_scrOscilloscope_cntRMS;
extern lv_obj_t *ui_scrOscilloscope_lblRMS;
extern lv_obj_t *ui_scrOscilloscope_lblRmsValue;
extern lv_obj_t *ui_scrOscilloscope_lblRmsUnit;
extern lv_obj_t *ui_scrOscilloscope_cntFrequency;
extern lv_obj_t *ui_scrOscilloscope_lblFrequency;
extern lv_obj_t *ui_scrOscilloscope_lblFrequencyValue;
extern lv_obj_t *ui_scrOscilloscope_lblFrequencyUnit;
extern lv_obj_t *ui_scrOscilloscope_cntTimeDiv;
extern lv_obj_t *ui_scrOscilloscope_lblTimeDiv;
extern lv_obj_t *ui_scrOscilloscope_lblTimeDivValue;
extern lv_obj_t *ui_scrOscilloscope_lblTimeDivValueUnit;
extern lv_obj_t *ui_scrOscilloscope_chartView;
extern lv_obj_t *ui_scrOscilloscope_chartView_Xaxis;
extern lv_obj_t *ui_scrOscilloscope_chartView_Yaxis1;
extern lv_obj_t *ui_scrOscilloscope_chartView_Yaxis2;
extern lv_obj_t *ui_scrOscilloscope_lineH1;
extern lv_obj_t *ui_scrOscilloscope_lineH2;
extern lv_obj_t *ui_scrOscilloscope_lineH3;
extern lv_obj_t *ui_scrOscilloscope_lineV1;
extern lv_obj_t *ui_scrOscilloscope_lineV2;
extern lv_obj_t *ui_scrOscilloscope_lineV3;
extern lv_obj_t *ui_scrOscilloscope_lineV4;
extern lv_obj_t *ui_scrOscilloscope_lineV5;
extern lv_obj_t *ui_scrOscilloscope_lineV6;
extern lv_obj_t *ui_scrOscilloscope_lineV7;
extern lv_obj_t *ui_scrOscilloscope_lineV8;
extern lv_obj_t *ui_scrOscilloscope_cntYLabels;
extern lv_obj_t *ui_scrOscilloscope_lblMiddle;
extern lv_obj_t *ui_scrOscilloscope_lblUnit;
extern lv_obj_t *ui_scrOscilloscope_lblTop;
extern lv_obj_t *ui_scrOscilloscope_lblBot;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

