// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "../ui.h"

lv_obj_t *ui_scrDatetime = NULL;lv_obj_t *ui_scrDatetime_contTopBar = NULL;lv_obj_t *ui_scrDatetime_lblDatime = NULL;lv_obj_t *ui_scrDatetime_btnBack = NULL;lv_obj_t *ui_scrDatetime_lblDate = NULL;lv_obj_t *ui_scrDatetime_cntDay = NULL;lv_obj_t *ui_scrDatetime_dayUp = NULL;lv_obj_t *ui_scrDatetime_lblDayV = NULL;lv_obj_t *ui_scrDatetime_dayDown = NULL;lv_obj_t *ui_scrDatetime_lblDay = NULL;lv_obj_t *ui_scrDatetime_cntMonth = NULL;lv_obj_t *ui_scrDatetime_monthUp = NULL;lv_obj_t *ui_scrDatetime_lblMonthV = NULL;lv_obj_t *ui_scrDatetime_monthDown = NULL;lv_obj_t *ui_scrDatetime_lblMonth = NULL;lv_obj_t *ui_scrDatetime_cntYear = NULL;lv_obj_t *ui_scrDatetime_yearUp = NULL;lv_obj_t *ui_scrDatetime_lblYearV = NULL;lv_obj_t *ui_scrDatetime_yearDown = NULL;lv_obj_t *ui_scrDatetime_lblYear = NULL;lv_obj_t *ui_scrDatetime_vline = NULL;lv_obj_t *ui_scrDatetime_lblTime = NULL;lv_obj_t *ui_scrDatetime_cntHour = NULL;lv_obj_t *ui_scrDatetime_hourUp = NULL;lv_obj_t *ui_scrDatetime_lblHourV = NULL;lv_obj_t *ui_scrDatetime_hourDown = NULL;lv_obj_t *ui_scrDatetime_lblHour = NULL;lv_obj_t *ui_scrDatetime_cntMin = NULL;lv_obj_t *ui_scrDatetime_minUp = NULL;lv_obj_t *ui_scrDatetime_lblMinV = NULL;lv_obj_t *ui_scrDatetime_minDown = NULL;lv_obj_t *ui_scrDatetime_lblMin = NULL;lv_obj_t *ui_scrDatetime_btnSave = NULL;lv_obj_t *ui_scrDatetime_iconSave = NULL;lv_obj_t *ui_scrDatetime_lblSave = NULL;lv_obj_t *ui_scrDatetime_cntBottomInfo = NULL;lv_obj_t *ui_scrDatetime_circle = NULL;lv_obj_t *ui_scrDatetime_lblBottomInfo = NULL;
// event funtions
void ui_event_scrDatetime_btnBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_scrSettings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_scrSettings_screen_init);
}
}

// build funtions

void ui_scrDatetime_screen_init(void)
{
ui_scrDatetime = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrDatetime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);

ui_scrDatetime_contTopBar = ui_contTopBar_create(ui_scrDatetime);
lv_obj_set_x( ui_scrDatetime_contTopBar, 0 );
lv_obj_set_y( ui_scrDatetime_contTopBar, 0 );

ui_scrDatetime_lblDatime = lv_label_create(ui_scrDatetime);
lv_obj_set_width( ui_scrDatetime_lblDatime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrDatetime_lblDatime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrDatetime_lblDatime, 52 );
lv_obj_set_y( ui_scrDatetime_lblDatime, 41 );
lv_label_set_text(ui_scrDatetime_lblDatime,"Fecha y Hora\n");
ui_object_set_themeable_style_property(ui_scrDatetime_lblDatime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDatime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrDatetime_lblDatime, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrDatetime_lblDatime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblDatime, &ui_font_SansBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrDatetime_btnBack = lv_image_create(ui_scrDatetime);
lv_image_set_src(ui_scrDatetime_btnBack, &ui_img_icons_ic_back_png);
lv_obj_set_width( ui_scrDatetime_btnBack, 28);
lv_obj_set_height( ui_scrDatetime_btnBack, 28);
lv_obj_set_x( ui_scrDatetime_btnBack, 14 );
lv_obj_set_y( ui_scrDatetime_btnBack, 37 );
lv_obj_add_flag( ui_scrDatetime_btnBack, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_btnBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_btnBack,85);
lv_obj_set_style_radius(ui_scrDatetime_btnBack, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Card);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Card);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrDatetime_btnBack, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblDate = lv_label_create(ui_scrDatetime);
lv_obj_set_width( ui_scrDatetime_lblDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrDatetime_lblDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrDatetime_lblDate, 132 );
lv_obj_set_y( ui_scrDatetime_lblDate, 92 );
lv_label_set_text(ui_scrDatetime_lblDate,"FECHA");
ui_object_set_themeable_style_property(ui_scrDatetime_lblDate, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDate, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_letter_space(ui_scrDatetime_lblDate, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrDatetime_lblDate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblDate, &ui_font_SansBold10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrDatetime_cntDay = lv_obj_create(ui_scrDatetime);
lv_obj_remove_style_all(ui_scrDatetime_cntDay);
lv_obj_set_width( ui_scrDatetime_cntDay, 60);
lv_obj_set_height( ui_scrDatetime_cntDay, 120);
lv_obj_set_x( ui_scrDatetime_cntDay, 50 );
lv_obj_set_y( ui_scrDatetime_cntDay, 114 );
lv_obj_remove_flag( ui_scrDatetime_cntDay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrDatetime_dayUp = lv_image_create(ui_scrDatetime_cntDay);
lv_image_set_src(ui_scrDatetime_dayUp, &ui_img_icons_ic_chevup_png);
lv_obj_set_width( ui_scrDatetime_dayUp, 15);
lv_obj_set_height( ui_scrDatetime_dayUp, 15);
lv_obj_set_align( ui_scrDatetime_dayUp, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_scrDatetime_dayUp, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_dayUp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_dayUp,80);
ui_object_set_themeable_style_property(ui_scrDatetime_dayUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_dayUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_dayUp, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_dayUp, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblDayV = lv_label_create(ui_scrDatetime_cntDay);
lv_obj_set_width( ui_scrDatetime_lblDayV, 46);
lv_obj_set_height( ui_scrDatetime_lblDayV, 51);
lv_obj_set_x( ui_scrDatetime_lblDayV, 0 );
lv_obj_set_y( ui_scrDatetime_lblDayV, -15 );
lv_obj_set_align( ui_scrDatetime_lblDayV, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrDatetime_lblDayV,"\n13");
ui_object_set_themeable_style_property(ui_scrDatetime_lblDayV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDayV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_align(ui_scrDatetime_lblDayV, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblDayV, &ui_font_MonoBold24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_scrDatetime_lblDayV, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrDatetime_lblDayV, lv_color_hex(0x080B10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrDatetime_lblDayV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDayV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDayV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrDatetime_lblDayV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDayV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDayV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDayV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDayV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDayV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDayV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);

ui_scrDatetime_dayDown = lv_image_create(ui_scrDatetime_cntDay);
lv_image_set_src(ui_scrDatetime_dayDown, &ui_img_icons_ic_chevdown_png);
lv_obj_set_width( ui_scrDatetime_dayDown, 15);
lv_obj_set_height( ui_scrDatetime_dayDown, 15);
lv_obj_set_x( ui_scrDatetime_dayDown, 0 );
lv_obj_set_y( ui_scrDatetime_dayDown, 25 );
lv_obj_set_align( ui_scrDatetime_dayDown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_scrDatetime_dayDown, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_dayDown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_dayDown,80);
ui_object_set_themeable_style_property(ui_scrDatetime_dayDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_dayDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_dayDown, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_dayDown, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblDay = lv_label_create(ui_scrDatetime_cntDay);
lv_obj_set_width( ui_scrDatetime_lblDay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrDatetime_lblDay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrDatetime_lblDay, 0 );
lv_obj_set_y( ui_scrDatetime_lblDay, -10 );
lv_obj_set_align( ui_scrDatetime_lblDay, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_scrDatetime_lblDay,"DIA");
ui_object_set_themeable_style_property(ui_scrDatetime_lblDay, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblDay, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_letter_space(ui_scrDatetime_lblDay, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrDatetime_lblDay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblDay, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrDatetime_cntMonth = lv_obj_create(ui_scrDatetime);
lv_obj_remove_style_all(ui_scrDatetime_cntMonth);
lv_obj_set_width( ui_scrDatetime_cntMonth, 60);
lv_obj_set_height( ui_scrDatetime_cntMonth, 120);
lv_obj_set_x( ui_scrDatetime_cntMonth, 120 );
lv_obj_set_y( ui_scrDatetime_cntMonth, 114 );
lv_obj_remove_flag( ui_scrDatetime_cntMonth, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrDatetime_monthUp = lv_image_create(ui_scrDatetime_cntMonth);
lv_image_set_src(ui_scrDatetime_monthUp, &ui_img_icons_ic_chevup_png);
lv_obj_set_width( ui_scrDatetime_monthUp, 15);
lv_obj_set_height( ui_scrDatetime_monthUp, 15);
lv_obj_set_align( ui_scrDatetime_monthUp, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_scrDatetime_monthUp, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_monthUp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_monthUp,80);
ui_object_set_themeable_style_property(ui_scrDatetime_monthUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_monthUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_monthUp, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_monthUp, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblMonthV = lv_label_create(ui_scrDatetime_cntMonth);
lv_obj_set_width( ui_scrDatetime_lblMonthV, 46);
lv_obj_set_height( ui_scrDatetime_lblMonthV, 51);
lv_obj_set_x( ui_scrDatetime_lblMonthV, 0 );
lv_obj_set_y( ui_scrDatetime_lblMonthV, -15 );
lv_obj_set_align( ui_scrDatetime_lblMonthV, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrDatetime_lblMonthV,"\n06");
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonthV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonthV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_align(ui_scrDatetime_lblMonthV, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblMonthV, &ui_font_MonoBold24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_scrDatetime_lblMonthV, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrDatetime_lblMonthV, lv_color_hex(0x080B10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrDatetime_lblMonthV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonthV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonthV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrDatetime_lblMonthV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonthV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonthV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonthV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonthV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonthV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonthV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);

ui_scrDatetime_monthDown = lv_image_create(ui_scrDatetime_cntMonth);
lv_image_set_src(ui_scrDatetime_monthDown, &ui_img_icons_ic_chevdown_png);
lv_obj_set_width( ui_scrDatetime_monthDown, 15);
lv_obj_set_height( ui_scrDatetime_monthDown, 15);
lv_obj_set_x( ui_scrDatetime_monthDown, 0 );
lv_obj_set_y( ui_scrDatetime_monthDown, 25 );
lv_obj_set_align( ui_scrDatetime_monthDown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_scrDatetime_monthDown, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_monthDown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_monthDown,80);
ui_object_set_themeable_style_property(ui_scrDatetime_monthDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_monthDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_monthDown, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_monthDown, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblMonth = lv_label_create(ui_scrDatetime_cntMonth);
lv_obj_set_width( ui_scrDatetime_lblMonth, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrDatetime_lblMonth, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrDatetime_lblMonth, 0 );
lv_obj_set_y( ui_scrDatetime_lblMonth, -10 );
lv_obj_set_align( ui_scrDatetime_lblMonth, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_scrDatetime_lblMonth,"MES");
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonth, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMonth, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_letter_space(ui_scrDatetime_lblMonth, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrDatetime_lblMonth, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblMonth, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrDatetime_cntYear = lv_obj_create(ui_scrDatetime);
lv_obj_remove_style_all(ui_scrDatetime_cntYear);
lv_obj_set_width( ui_scrDatetime_cntYear, 60);
lv_obj_set_height( ui_scrDatetime_cntYear, 120);
lv_obj_set_x( ui_scrDatetime_cntYear, 190 );
lv_obj_set_y( ui_scrDatetime_cntYear, 114 );
lv_obj_remove_flag( ui_scrDatetime_cntYear, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrDatetime_yearUp = lv_image_create(ui_scrDatetime_cntYear);
lv_image_set_src(ui_scrDatetime_yearUp, &ui_img_icons_ic_chevup_png);
lv_obj_set_width( ui_scrDatetime_yearUp, 15);
lv_obj_set_height( ui_scrDatetime_yearUp, 15);
lv_obj_set_align( ui_scrDatetime_yearUp, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_scrDatetime_yearUp, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_yearUp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_yearUp,80);
ui_object_set_themeable_style_property(ui_scrDatetime_yearUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_yearUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_yearUp, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_yearUp, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblYearV = lv_label_create(ui_scrDatetime_cntYear);
lv_obj_set_width( ui_scrDatetime_lblYearV, 46);
lv_obj_set_height( ui_scrDatetime_lblYearV, 51);
lv_obj_set_x( ui_scrDatetime_lblYearV, 0 );
lv_obj_set_y( ui_scrDatetime_lblYearV, -15 );
lv_obj_set_align( ui_scrDatetime_lblYearV, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrDatetime_lblYearV,"\n26");
ui_object_set_themeable_style_property(ui_scrDatetime_lblYearV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblYearV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_align(ui_scrDatetime_lblYearV, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblYearV, &ui_font_MonoBold24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_scrDatetime_lblYearV, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrDatetime_lblYearV, lv_color_hex(0x080B10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrDatetime_lblYearV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_lblYearV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrDatetime_lblYearV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrDatetime_lblYearV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_lblYearV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_lblYearV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_lblYearV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblYearV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblYearV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblYearV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);

ui_scrDatetime_yearDown = lv_image_create(ui_scrDatetime_cntYear);
lv_image_set_src(ui_scrDatetime_yearDown, &ui_img_icons_ic_chevdown_png);
lv_obj_set_width( ui_scrDatetime_yearDown, 15);
lv_obj_set_height( ui_scrDatetime_yearDown, 15);
lv_obj_set_x( ui_scrDatetime_yearDown, 0 );
lv_obj_set_y( ui_scrDatetime_yearDown, 25 );
lv_obj_set_align( ui_scrDatetime_yearDown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_scrDatetime_yearDown, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_yearDown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_yearDown,80);
ui_object_set_themeable_style_property(ui_scrDatetime_yearDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_yearDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_yearDown, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_yearDown, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblYear = lv_label_create(ui_scrDatetime_cntYear);
lv_obj_set_width( ui_scrDatetime_lblYear, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrDatetime_lblYear, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrDatetime_lblYear, 0 );
lv_obj_set_y( ui_scrDatetime_lblYear, -10 );
lv_obj_set_align( ui_scrDatetime_lblYear, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_scrDatetime_lblYear,"AÑO");
ui_object_set_themeable_style_property(ui_scrDatetime_lblYear, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblYear, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_letter_space(ui_scrDatetime_lblYear, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrDatetime_lblYear, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblYear, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrDatetime_vline = lv_label_create(ui_scrDatetime);
lv_obj_set_width( ui_scrDatetime_vline, 1);
lv_obj_set_height( ui_scrDatetime_vline, 120);
lv_obj_set_x( ui_scrDatetime_vline, 20 );
lv_obj_set_y( ui_scrDatetime_vline, 114 );
lv_obj_set_align( ui_scrDatetime_vline, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_scrDatetime_vline,"");
ui_object_set_themeable_style_property(ui_scrDatetime_vline, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrDatetime_vline, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_border_width(ui_scrDatetime_vline, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrDatetime_lblTime = lv_label_create(ui_scrDatetime);
lv_obj_set_width( ui_scrDatetime_lblTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrDatetime_lblTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrDatetime_lblTime, 328 );
lv_obj_set_y( ui_scrDatetime_lblTime, 92 );
lv_label_set_text(ui_scrDatetime_lblTime,"HORA");
ui_object_set_themeable_style_property(ui_scrDatetime_lblTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_letter_space(ui_scrDatetime_lblTime, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrDatetime_lblTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblTime, &ui_font_SansBold10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrDatetime_cntHour = lv_obj_create(ui_scrDatetime);
lv_obj_remove_style_all(ui_scrDatetime_cntHour);
lv_obj_set_width( ui_scrDatetime_cntHour, 60);
lv_obj_set_height( ui_scrDatetime_cntHour, 120);
lv_obj_set_x( ui_scrDatetime_cntHour, 280 );
lv_obj_set_y( ui_scrDatetime_cntHour, 114 );
lv_obj_remove_flag( ui_scrDatetime_cntHour, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrDatetime_hourUp = lv_image_create(ui_scrDatetime_cntHour);
lv_image_set_src(ui_scrDatetime_hourUp, &ui_img_icons_ic_chevup_png);
lv_obj_set_width( ui_scrDatetime_hourUp, 15);
lv_obj_set_height( ui_scrDatetime_hourUp, 15);
lv_obj_set_align( ui_scrDatetime_hourUp, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_scrDatetime_hourUp, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_hourUp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_hourUp,80);
ui_object_set_themeable_style_property(ui_scrDatetime_hourUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_hourUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_hourUp, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_hourUp, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblHourV = lv_label_create(ui_scrDatetime_cntHour);
lv_obj_set_width( ui_scrDatetime_lblHourV, 46);
lv_obj_set_height( ui_scrDatetime_lblHourV, 51);
lv_obj_set_x( ui_scrDatetime_lblHourV, 0 );
lv_obj_set_y( ui_scrDatetime_lblHourV, -15 );
lv_obj_set_align( ui_scrDatetime_lblHourV, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrDatetime_lblHourV,"\n14");
ui_object_set_themeable_style_property(ui_scrDatetime_lblHourV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblHourV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_align(ui_scrDatetime_lblHourV, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblHourV, &ui_font_MonoBold24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_scrDatetime_lblHourV, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrDatetime_lblHourV, lv_color_hex(0x080B10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrDatetime_lblHourV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_lblHourV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrDatetime_lblHourV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrDatetime_lblHourV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_lblHourV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_lblHourV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_lblHourV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblHourV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblHourV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblHourV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);

ui_scrDatetime_hourDown = lv_image_create(ui_scrDatetime_cntHour);
lv_image_set_src(ui_scrDatetime_hourDown, &ui_img_icons_ic_chevdown_png);
lv_obj_set_width( ui_scrDatetime_hourDown, 15);
lv_obj_set_height( ui_scrDatetime_hourDown, 15);
lv_obj_set_x( ui_scrDatetime_hourDown, 0 );
lv_obj_set_y( ui_scrDatetime_hourDown, 25 );
lv_obj_set_align( ui_scrDatetime_hourDown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_scrDatetime_hourDown, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_hourDown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_hourDown,80);
ui_object_set_themeable_style_property(ui_scrDatetime_hourDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_hourDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_hourDown, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_hourDown, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblHour = lv_label_create(ui_scrDatetime_cntHour);
lv_obj_set_width( ui_scrDatetime_lblHour, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrDatetime_lblHour, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrDatetime_lblHour, 0 );
lv_obj_set_y( ui_scrDatetime_lblHour, -10 );
lv_obj_set_align( ui_scrDatetime_lblHour, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_scrDatetime_lblHour,"HORA");
ui_object_set_themeable_style_property(ui_scrDatetime_lblHour, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblHour, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_letter_space(ui_scrDatetime_lblHour, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrDatetime_lblHour, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblHour, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrDatetime_cntMin = lv_obj_create(ui_scrDatetime);
lv_obj_remove_style_all(ui_scrDatetime_cntMin);
lv_obj_set_width( ui_scrDatetime_cntMin, 60);
lv_obj_set_height( ui_scrDatetime_cntMin, 120);
lv_obj_set_x( ui_scrDatetime_cntMin, 350 );
lv_obj_set_y( ui_scrDatetime_cntMin, 114 );
lv_obj_remove_flag( ui_scrDatetime_cntMin, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrDatetime_minUp = lv_image_create(ui_scrDatetime_cntMin);
lv_image_set_src(ui_scrDatetime_minUp, &ui_img_icons_ic_chevup_png);
lv_obj_set_width( ui_scrDatetime_minUp, 15);
lv_obj_set_height( ui_scrDatetime_minUp, 15);
lv_obj_set_align( ui_scrDatetime_minUp, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_scrDatetime_minUp, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_minUp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_minUp,80);
ui_object_set_themeable_style_property(ui_scrDatetime_minUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_minUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_minUp, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_minUp, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblMinV = lv_label_create(ui_scrDatetime_cntMin);
lv_obj_set_width( ui_scrDatetime_lblMinV, 46);
lv_obj_set_height( ui_scrDatetime_lblMinV, 51);
lv_obj_set_x( ui_scrDatetime_lblMinV, 0 );
lv_obj_set_y( ui_scrDatetime_lblMinV, -15 );
lv_obj_set_align( ui_scrDatetime_lblMinV, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrDatetime_lblMinV,"\n32");
ui_object_set_themeable_style_property(ui_scrDatetime_lblMinV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMinV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_align(ui_scrDatetime_lblMinV, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblMinV, &ui_font_MonoBold24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_scrDatetime_lblMinV, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrDatetime_lblMinV, lv_color_hex(0x080B10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrDatetime_lblMinV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMinV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMinV, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrDatetime_lblMinV, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMinV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMinV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMinV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMinV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMinV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMinV, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);

ui_scrDatetime_minDown = lv_image_create(ui_scrDatetime_cntMin);
lv_image_set_src(ui_scrDatetime_minDown, &ui_img_icons_ic_chevdown_png);
lv_obj_set_width( ui_scrDatetime_minDown, 15);
lv_obj_set_height( ui_scrDatetime_minDown, 15);
lv_obj_set_x( ui_scrDatetime_minDown, 0 );
lv_obj_set_y( ui_scrDatetime_minDown, 25 );
lv_obj_set_align( ui_scrDatetime_minDown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_scrDatetime_minDown, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_minDown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_minDown,80);
ui_object_set_themeable_style_property(ui_scrDatetime_minDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_minDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_minDown, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_minDown, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblMin = lv_label_create(ui_scrDatetime_cntMin);
lv_obj_set_width( ui_scrDatetime_lblMin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrDatetime_lblMin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrDatetime_lblMin, 0 );
lv_obj_set_y( ui_scrDatetime_lblMin, -10 );
lv_obj_set_align( ui_scrDatetime_lblMin, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_scrDatetime_lblMin,"MINUTO");
ui_object_set_themeable_style_property(ui_scrDatetime_lblMin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrDatetime_lblMin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_letter_space(ui_scrDatetime_lblMin, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrDatetime_lblMin, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrDatetime_lblMin, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrDatetime_btnSave = lv_obj_create(ui_scrDatetime);
lv_obj_remove_style_all(ui_scrDatetime_btnSave);
lv_obj_set_width( ui_scrDatetime_btnSave, 150);
lv_obj_set_height( ui_scrDatetime_btnSave, 30);
lv_obj_set_x( ui_scrDatetime_btnSave, 314 );
lv_obj_set_y( ui_scrDatetime_btnSave, 250 );
lv_obj_remove_flag( ui_scrDatetime_btnSave, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrDatetime_btnSave, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_btnSave, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_btnSave, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_btnSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_btnSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_btnSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_btnSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);
lv_obj_set_style_border_width(ui_scrDatetime_btnSave, 1, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_scrDatetime_iconSave = lv_image_create(ui_scrDatetime_btnSave);
lv_image_set_src(ui_scrDatetime_iconSave, &ui_img_icons_ic_check_png);
lv_obj_set_width( ui_scrDatetime_iconSave, 15);
lv_obj_set_height( ui_scrDatetime_iconSave, 15);
lv_obj_set_x( ui_scrDatetime_iconSave, 38 );
lv_obj_set_y( ui_scrDatetime_iconSave, 0 );
lv_obj_set_align( ui_scrDatetime_iconSave, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_scrDatetime_iconSave, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrDatetime_iconSave, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrDatetime_iconSave,80);
ui_object_set_themeable_style_property(ui_scrDatetime_iconSave, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrDatetime_iconSave, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrDatetime_iconSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_iconSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrDatetime_iconSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_iconSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_iconSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_iconSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_lblSave = lv_label_create(ui_scrDatetime_btnSave);
lv_obj_set_width( ui_scrDatetime_lblSave, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrDatetime_lblSave, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrDatetime_lblSave, 60 );
lv_obj_set_y( ui_scrDatetime_lblSave, 0 );
lv_obj_set_align( ui_scrDatetime_lblSave, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_scrDatetime_lblSave,"Guardar");
ui_object_set_themeable_style_property(ui_scrDatetime_lblSave, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrDatetime_lblSave, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
lv_obj_set_style_text_font(ui_scrDatetime_lblSave, &ui_font_SansBold13, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_lblSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrDatetime_lblSave, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foco);

ui_scrDatetime_cntBottomInfo = lv_obj_create(ui_scrDatetime);
lv_obj_remove_style_all(ui_scrDatetime_cntBottomInfo);
lv_obj_set_width( ui_scrDatetime_cntBottomInfo, 480);
lv_obj_set_height( ui_scrDatetime_cntBottomInfo, 26);
lv_obj_set_x( ui_scrDatetime_cntBottomInfo, 0 );
lv_obj_set_y( ui_scrDatetime_cntBottomInfo, 294 );
lv_obj_set_align( ui_scrDatetime_cntBottomInfo, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_scrDatetime_cntBottomInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrDatetime_cntBottomInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Panel);
ui_object_set_themeable_style_property(ui_scrDatetime_cntBottomInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Panel);
ui_object_set_themeable_style_property(ui_scrDatetime_cntBottomInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrDatetime_cntBottomInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrDatetime_cntBottomInfo, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrDatetime_circle = lv_label_create(ui_scrDatetime_cntBottomInfo);
lv_obj_set_width( ui_scrDatetime_circle, 12);
lv_obj_set_height( ui_scrDatetime_circle, 12);
lv_obj_set_x( ui_scrDatetime_circle, 65 );
lv_obj_set_y( ui_scrDatetime_circle, 0 );
lv_obj_set_align( ui_scrDatetime_circle, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_scrDatetime_circle,"");
lv_obj_set_style_radius(ui_scrDatetime_circle, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrDatetime_circle, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrDatetime_circle, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_border_width(ui_scrDatetime_circle, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrDatetime_lblBottomInfo = lv_label_create(ui_scrDatetime_cntBottomInfo);
lv_obj_set_width( ui_scrDatetime_lblBottomInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrDatetime_lblBottomInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrDatetime_lblBottomInfo, 0 );
lv_obj_set_y( ui_scrDatetime_lblBottomInfo, -1 );
lv_obj_set_align( ui_scrDatetime_lblBottomInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrDatetime_lblBottomInfo,"Gire para navegar/modificar - Pulse para bloquear/desbloquear");
ui_object_set_themeable_style_property(ui_scrDatetime_lblBottomInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrDatetime_lblBottomInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_font(ui_scrDatetime_lblBottomInfo, &ui_font_SansReg11, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_scrDatetime_btnBack, ui_event_scrDatetime_btnBack, LV_EVENT_ALL, NULL);

}

void ui_scrDatetime_screen_destroy(void)
{
   if (ui_scrDatetime) lv_obj_del(ui_scrDatetime);

// NULL screen variables
ui_scrDatetime= NULL;
ui_scrDatetime_contTopBar= NULL;
ui_scrDatetime_lblDatime= NULL;
ui_scrDatetime_btnBack= NULL;
ui_scrDatetime_lblDate= NULL;
ui_scrDatetime_cntDay= NULL;
ui_scrDatetime_dayUp= NULL;
ui_scrDatetime_lblDayV= NULL;
ui_scrDatetime_dayDown= NULL;
ui_scrDatetime_lblDay= NULL;
ui_scrDatetime_cntMonth= NULL;
ui_scrDatetime_monthUp= NULL;
ui_scrDatetime_lblMonthV= NULL;
ui_scrDatetime_monthDown= NULL;
ui_scrDatetime_lblMonth= NULL;
ui_scrDatetime_cntYear= NULL;
ui_scrDatetime_yearUp= NULL;
ui_scrDatetime_lblYearV= NULL;
ui_scrDatetime_yearDown= NULL;
ui_scrDatetime_lblYear= NULL;
ui_scrDatetime_vline= NULL;
ui_scrDatetime_lblTime= NULL;
ui_scrDatetime_cntHour= NULL;
ui_scrDatetime_hourUp= NULL;
ui_scrDatetime_lblHourV= NULL;
ui_scrDatetime_hourDown= NULL;
ui_scrDatetime_lblHour= NULL;
ui_scrDatetime_cntMin= NULL;
ui_scrDatetime_minUp= NULL;
ui_scrDatetime_lblMinV= NULL;
ui_scrDatetime_minDown= NULL;
ui_scrDatetime_lblMin= NULL;
ui_scrDatetime_btnSave= NULL;
ui_scrDatetime_iconSave= NULL;
ui_scrDatetime_lblSave= NULL;
ui_scrDatetime_cntBottomInfo= NULL;
ui_scrDatetime_circle= NULL;
ui_scrDatetime_lblBottomInfo= NULL;

}
