// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "../ui.h"

lv_obj_t *ui_scrSettings = NULL;lv_obj_t *ui_scrSettings_contTopBar2 = NULL;lv_obj_t *ui_scrSettings_lblSettings = NULL;lv_obj_t *ui_scrSettings_btnBack = NULL;lv_obj_t *ui_scrSettings_cntDatetime = NULL;lv_obj_t *ui_scrSettings_iconDatetime = NULL;lv_obj_t *ui_scrSettings_lblDatetime = NULL;lv_obj_t *ui_scrSettings_lblDatetimeBrief = NULL;lv_obj_t *ui_scrSettings_iconDatetimeEnter = NULL;lv_obj_t *ui_scrSettings_cntScreen = NULL;lv_obj_t *ui_scrSettings_iconScreen = NULL;lv_obj_t *ui_scrSettings_lblScreen = NULL;lv_obj_t *ui_scrSettings_lblScreenBrief = NULL;lv_obj_t *ui_scrSettings_iconScreenEnter = NULL;lv_obj_t *ui_scrSettings_cntMeasure = NULL;lv_obj_t *ui_scrSettings_iconMeasure = NULL;lv_obj_t *ui_scrSettings_lblMeasure = NULL;lv_obj_t *ui_scrSettings_lblMeasureBrief = NULL;lv_obj_t *ui_scrSettings_iconMeasureEnter = NULL;lv_obj_t *ui_scrSettings_cntInfo = NULL;lv_obj_t *ui_scrSettings_iconInfo = NULL;lv_obj_t *ui_scrSettings_lblInfo = NULL;lv_obj_t *ui_scrSettings_lblInfoBrief = NULL;lv_obj_t *ui_scrSettings_iconInfoEnter = NULL;
// event funtions
void ui_event_scrSettings_btnBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_scrMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_scrMenu_screen_init);
}
}

// build funtions

void ui_scrSettings_screen_init(void)
{
ui_scrSettings = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrSettings, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrSettings, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);

ui_scrSettings_contTopBar2 = ui_contTopBar_create(ui_scrSettings);
lv_obj_set_x( ui_scrSettings_contTopBar2, 0 );
lv_obj_set_y( ui_scrSettings_contTopBar2, 0 );

ui_scrSettings_lblSettings = lv_label_create(ui_scrSettings);
lv_obj_set_width( ui_scrSettings_lblSettings, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrSettings_lblSettings, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrSettings_lblSettings, 52 );
lv_obj_set_y( ui_scrSettings_lblSettings, 41 );
lv_label_set_text(ui_scrSettings_lblSettings,"Ajustes");
ui_object_set_themeable_style_property(ui_scrSettings_lblSettings, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrSettings_lblSettings, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrSettings_lblSettings, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrSettings_lblSettings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrSettings_lblSettings, &ui_font_SansBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrSettings_btnBack = lv_image_create(ui_scrSettings);
lv_image_set_src(ui_scrSettings_btnBack, &ui_img_icons_ic_back_png);
lv_obj_set_width( ui_scrSettings_btnBack, 28);
lv_obj_set_height( ui_scrSettings_btnBack, 28);
lv_obj_set_x( ui_scrSettings_btnBack, 14 );
lv_obj_set_y( ui_scrSettings_btnBack, 37 );
lv_obj_add_flag( ui_scrSettings_btnBack, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrSettings_btnBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrSettings_btnBack,85);
lv_obj_set_style_radius(ui_scrSettings_btnBack, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Card);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Card);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrSettings_btnBack, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_cntDatetime = lv_obj_create(ui_scrSettings);
lv_obj_remove_style_all(ui_scrSettings_cntDatetime);
lv_obj_set_width( ui_scrSettings_cntDatetime, 222);
lv_obj_set_height( ui_scrSettings_cntDatetime, 50);
lv_obj_set_x( ui_scrSettings_cntDatetime, 14 );
lv_obj_set_y( ui_scrSettings_cntDatetime, 72 );
lv_obj_remove_flag( ui_scrSettings_cntDatetime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrSettings_cntDatetime, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_cntDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Card);
ui_object_set_themeable_style_property(ui_scrSettings_cntDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Card);
ui_object_set_themeable_style_property(ui_scrSettings_cntDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrSettings_cntDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrSettings_cntDatetime, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_cntDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);
lv_obj_set_style_border_width(ui_scrSettings_cntDatetime, 1, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_scrSettings_iconDatetime = lv_image_create(ui_scrSettings_cntDatetime);
lv_image_set_src(ui_scrSettings_iconDatetime, &ui_img_icons_ic_datetime_png);
lv_obj_set_width( ui_scrSettings_iconDatetime, 32);
lv_obj_set_height( ui_scrSettings_iconDatetime, 32);
lv_obj_set_x( ui_scrSettings_iconDatetime, 12 );
lv_obj_set_y( ui_scrSettings_iconDatetime, 9 );
lv_obj_add_flag( ui_scrSettings_iconDatetime, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrSettings_iconDatetime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrSettings_iconDatetime,96);
lv_obj_set_style_radius(ui_scrSettings_iconDatetime, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrSettings_iconDatetime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrSettings_iconDatetime, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrSettings_iconDatetime, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_lblDatetime = lv_label_create(ui_scrSettings_cntDatetime);
lv_obj_set_width( ui_scrSettings_lblDatetime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrSettings_lblDatetime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrSettings_lblDatetime, 54 );
lv_obj_set_y( ui_scrSettings_lblDatetime, 10 );
lv_label_set_text(ui_scrSettings_lblDatetime,"Fecha y Hora");
ui_object_set_themeable_style_property(ui_scrSettings_lblDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrSettings_lblDatetime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_font(ui_scrSettings_lblDatetime, &ui_font_SansBold13, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_lblDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrSettings_lblDatetime, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);

ui_scrSettings_lblDatetimeBrief = lv_label_create(ui_scrSettings_cntDatetime);
lv_obj_set_width( ui_scrSettings_lblDatetimeBrief, 120);
lv_obj_set_height( ui_scrSettings_lblDatetimeBrief, 10);
lv_obj_set_x( ui_scrSettings_lblDatetimeBrief, 54 );
lv_obj_set_y( ui_scrSettings_lblDatetimeBrief, 28 );
lv_label_set_long_mode(ui_scrSettings_lblDatetimeBrief,LV_LABEL_LONG_MODE_DOTS);
lv_label_set_text(ui_scrSettings_lblDatetimeBrief,"13/06/2026 - 14:32");
ui_object_set_themeable_style_property(ui_scrSettings_lblDatetimeBrief, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_lblDatetimeBrief, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrSettings_lblDatetimeBrief, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_lblDatetimeBrief, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_lblDatetimeBrief, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_iconDatetimeEnter = lv_image_create(ui_scrSettings_cntDatetime);
lv_image_set_src(ui_scrSettings_iconDatetimeEnter, &ui_img_icons_ic_chevright_png);
lv_obj_set_width( ui_scrSettings_iconDatetimeEnter, 15);
lv_obj_set_height( ui_scrSettings_iconDatetimeEnter, 15);
lv_obj_set_x( ui_scrSettings_iconDatetimeEnter, 195 );
lv_obj_set_y( ui_scrSettings_iconDatetimeEnter, 18 );
lv_obj_add_flag( ui_scrSettings_iconDatetimeEnter, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrSettings_iconDatetimeEnter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrSettings_iconDatetimeEnter,80);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetimeEnter, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetimeEnter, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetimeEnter, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconDatetimeEnter, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_cntScreen = lv_obj_create(ui_scrSettings);
lv_obj_remove_style_all(ui_scrSettings_cntScreen);
lv_obj_set_width( ui_scrSettings_cntScreen, 222);
lv_obj_set_height( ui_scrSettings_cntScreen, 50);
lv_obj_set_x( ui_scrSettings_cntScreen, 244 );
lv_obj_set_y( ui_scrSettings_cntScreen, 72 );
lv_obj_remove_flag( ui_scrSettings_cntScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrSettings_cntScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_cntScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Card);
ui_object_set_themeable_style_property(ui_scrSettings_cntScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Card);
ui_object_set_themeable_style_property(ui_scrSettings_cntScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrSettings_cntScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrSettings_cntScreen, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_cntScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);
lv_obj_set_style_border_width(ui_scrSettings_cntScreen, 1, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_scrSettings_iconScreen = lv_image_create(ui_scrSettings_cntScreen);
lv_image_set_src(ui_scrSettings_iconScreen, &ui_img_icons_ic_screen_png);
lv_obj_set_width( ui_scrSettings_iconScreen, 32);
lv_obj_set_height( ui_scrSettings_iconScreen, 32);
lv_obj_set_x( ui_scrSettings_iconScreen, 12 );
lv_obj_set_y( ui_scrSettings_iconScreen, 9 );
lv_obj_add_flag( ui_scrSettings_iconScreen, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrSettings_iconScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrSettings_iconScreen,96);
lv_obj_set_style_radius(ui_scrSettings_iconScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrSettings_iconScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrSettings_iconScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrSettings_iconScreen, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_lblScreen = lv_label_create(ui_scrSettings_cntScreen);
lv_obj_set_width( ui_scrSettings_lblScreen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrSettings_lblScreen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrSettings_lblScreen, 54 );
lv_obj_set_y( ui_scrSettings_lblScreen, 10 );
lv_label_set_text(ui_scrSettings_lblScreen,"Pantalla");
ui_object_set_themeable_style_property(ui_scrSettings_lblScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrSettings_lblScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_font(ui_scrSettings_lblScreen, &ui_font_SansBold13, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_lblScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrSettings_lblScreen, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);

ui_scrSettings_lblScreenBrief = lv_label_create(ui_scrSettings_cntScreen);
lv_obj_set_width( ui_scrSettings_lblScreenBrief, 120);
lv_obj_set_height( ui_scrSettings_lblScreenBrief, 10);
lv_obj_set_x( ui_scrSettings_lblScreenBrief, 54 );
lv_obj_set_y( ui_scrSettings_lblScreenBrief, 28 );
lv_label_set_long_mode(ui_scrSettings_lblScreenBrief,LV_LABEL_LONG_MODE_DOTS);
lv_label_set_text(ui_scrSettings_lblScreenBrief,"Brillo 80% - apagado 2 min");
ui_object_set_themeable_style_property(ui_scrSettings_lblScreenBrief, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_lblScreenBrief, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrSettings_lblScreenBrief, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_lblScreenBrief, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_lblScreenBrief, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_iconScreenEnter = lv_image_create(ui_scrSettings_cntScreen);
lv_image_set_src(ui_scrSettings_iconScreenEnter, &ui_img_icons_ic_chevright_png);
lv_obj_set_width( ui_scrSettings_iconScreenEnter, 15);
lv_obj_set_height( ui_scrSettings_iconScreenEnter, 15);
lv_obj_set_x( ui_scrSettings_iconScreenEnter, 195 );
lv_obj_set_y( ui_scrSettings_iconScreenEnter, 18 );
lv_obj_add_flag( ui_scrSettings_iconScreenEnter, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrSettings_iconScreenEnter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrSettings_iconScreenEnter,80);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreenEnter, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreenEnter, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreenEnter, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconScreenEnter, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_cntMeasure = lv_obj_create(ui_scrSettings);
lv_obj_remove_style_all(ui_scrSettings_cntMeasure);
lv_obj_set_width( ui_scrSettings_cntMeasure, 222);
lv_obj_set_height( ui_scrSettings_cntMeasure, 50);
lv_obj_set_x( ui_scrSettings_cntMeasure, 14 );
lv_obj_set_y( ui_scrSettings_cntMeasure, 130 );
lv_obj_remove_flag( ui_scrSettings_cntMeasure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrSettings_cntMeasure, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_cntMeasure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Card);
ui_object_set_themeable_style_property(ui_scrSettings_cntMeasure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Card);
ui_object_set_themeable_style_property(ui_scrSettings_cntMeasure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrSettings_cntMeasure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrSettings_cntMeasure, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_cntMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);
lv_obj_set_style_border_width(ui_scrSettings_cntMeasure, 1, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_scrSettings_iconMeasure = lv_image_create(ui_scrSettings_cntMeasure);
lv_image_set_src(ui_scrSettings_iconMeasure, &ui_img_icons_ic_bolt_png);
lv_obj_set_width( ui_scrSettings_iconMeasure, 32);
lv_obj_set_height( ui_scrSettings_iconMeasure, 32);
lv_obj_set_x( ui_scrSettings_iconMeasure, 12 );
lv_obj_set_y( ui_scrSettings_iconMeasure, 9 );
lv_obj_add_flag( ui_scrSettings_iconMeasure, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrSettings_iconMeasure, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrSettings_iconMeasure,96);
lv_obj_set_style_radius(ui_scrSettings_iconMeasure, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrSettings_iconMeasure, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrSettings_iconMeasure, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrSettings_iconMeasure, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_lblMeasure = lv_label_create(ui_scrSettings_cntMeasure);
lv_obj_set_width( ui_scrSettings_lblMeasure, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrSettings_lblMeasure, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrSettings_lblMeasure, 54 );
lv_obj_set_y( ui_scrSettings_lblMeasure, 10 );
lv_label_set_text(ui_scrSettings_lblMeasure,"Medición");
ui_object_set_themeable_style_property(ui_scrSettings_lblMeasure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrSettings_lblMeasure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_font(ui_scrSettings_lblMeasure, &ui_font_SansBold13, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_lblMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrSettings_lblMeasure, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);

ui_scrSettings_lblMeasureBrief = lv_label_create(ui_scrSettings_cntMeasure);
lv_obj_set_width( ui_scrSettings_lblMeasureBrief, 120);
lv_obj_set_height( ui_scrSettings_lblMeasureBrief, 10);
lv_obj_set_x( ui_scrSettings_lblMeasureBrief, 54 );
lv_obj_set_y( ui_scrSettings_lblMeasureBrief, 28 );
lv_label_set_long_mode(ui_scrSettings_lblMeasureBrief,LV_LABEL_LONG_MODE_DOTS);
lv_label_set_text(ui_scrSettings_lblMeasureBrief,"230 V - 50 Hz - pinza 100 A");
ui_object_set_themeable_style_property(ui_scrSettings_lblMeasureBrief, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_lblMeasureBrief, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrSettings_lblMeasureBrief, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_lblMeasureBrief, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_lblMeasureBrief, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_iconMeasureEnter = lv_image_create(ui_scrSettings_cntMeasure);
lv_image_set_src(ui_scrSettings_iconMeasureEnter, &ui_img_icons_ic_chevright_png);
lv_obj_set_width( ui_scrSettings_iconMeasureEnter, 15);
lv_obj_set_height( ui_scrSettings_iconMeasureEnter, 15);
lv_obj_set_x( ui_scrSettings_iconMeasureEnter, 195 );
lv_obj_set_y( ui_scrSettings_iconMeasureEnter, 18 );
lv_obj_add_flag( ui_scrSettings_iconMeasureEnter, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrSettings_iconMeasureEnter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrSettings_iconMeasureEnter,80);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasureEnter, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasureEnter, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasureEnter, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconMeasureEnter, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_cntInfo = lv_obj_create(ui_scrSettings);
lv_obj_remove_style_all(ui_scrSettings_cntInfo);
lv_obj_set_width( ui_scrSettings_cntInfo, 222);
lv_obj_set_height( ui_scrSettings_cntInfo, 50);
lv_obj_set_x( ui_scrSettings_cntInfo, 244 );
lv_obj_set_y( ui_scrSettings_cntInfo, 130 );
lv_obj_remove_flag( ui_scrSettings_cntInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrSettings_cntInfo, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_cntInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Card);
ui_object_set_themeable_style_property(ui_scrSettings_cntInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Card);
ui_object_set_themeable_style_property(ui_scrSettings_cntInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrSettings_cntInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrSettings_cntInfo, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_cntInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_cntInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);
lv_obj_set_style_border_width(ui_scrSettings_cntInfo, 1, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_scrSettings_iconInfo = lv_image_create(ui_scrSettings_cntInfo);
lv_image_set_src(ui_scrSettings_iconInfo, &ui_img_icons_ic_info_png);
lv_obj_set_width( ui_scrSettings_iconInfo, 32);
lv_obj_set_height( ui_scrSettings_iconInfo, 32);
lv_obj_set_x( ui_scrSettings_iconInfo, 12 );
lv_obj_set_y( ui_scrSettings_iconInfo, 9 );
lv_obj_add_flag( ui_scrSettings_iconInfo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrSettings_iconInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrSettings_iconInfo,96);
lv_obj_set_style_radius(ui_scrSettings_iconInfo, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_scrSettings_iconInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrSettings_iconInfo, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrSettings_iconInfo, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_lblInfo = lv_label_create(ui_scrSettings_cntInfo);
lv_obj_set_width( ui_scrSettings_lblInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrSettings_lblInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrSettings_lblInfo, 54 );
lv_obj_set_y( ui_scrSettings_lblInfo, 10 );
lv_label_set_text(ui_scrSettings_lblInfo,"Información");
ui_object_set_themeable_style_property(ui_scrSettings_lblInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrSettings_lblInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_font(ui_scrSettings_lblInfo, &ui_font_SansBold13, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_lblInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrSettings_lblInfo, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);

ui_scrSettings_lblInfoBrief = lv_label_create(ui_scrSettings_cntInfo);
lv_obj_set_width( ui_scrSettings_lblInfoBrief, 120);
lv_obj_set_height( ui_scrSettings_lblInfoBrief, 10);
lv_obj_set_x( ui_scrSettings_lblInfoBrief, 54 );
lv_obj_set_y( ui_scrSettings_lblInfoBrief, 28 );
lv_label_set_long_mode(ui_scrSettings_lblInfoBrief,LV_LABEL_LONG_MODE_DOTS);
lv_label_set_text(ui_scrSettings_lblInfoBrief,"Firmware v0.1.0 - S/N ATRI-001");
ui_object_set_themeable_style_property(ui_scrSettings_lblInfoBrief, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_lblInfoBrief, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrSettings_lblInfoBrief, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrSettings_lblInfoBrief, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_lblInfoBrief, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Foco);

ui_scrSettings_iconInfoEnter = lv_image_create(ui_scrSettings_cntInfo);
lv_image_set_src(ui_scrSettings_iconInfoEnter, &ui_img_icons_ic_chevright_png);
lv_obj_set_width( ui_scrSettings_iconInfoEnter, 15);
lv_obj_set_height( ui_scrSettings_iconInfoEnter, 15);
lv_obj_set_x( ui_scrSettings_iconInfoEnter, 195 );
lv_obj_set_y( ui_scrSettings_iconInfoEnter, 18 );
lv_obj_add_flag( ui_scrSettings_iconInfoEnter, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrSettings_iconInfoEnter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrSettings_iconInfoEnter,80);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfoEnter, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfoEnter, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfoEnter, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrSettings_iconInfoEnter, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

lv_obj_add_event_cb(ui_scrSettings_btnBack, ui_event_scrSettings_btnBack, LV_EVENT_ALL, NULL);

}

void ui_scrSettings_screen_destroy(void)
{
   if (ui_scrSettings) lv_obj_del(ui_scrSettings);

// NULL screen variables
ui_scrSettings= NULL;
ui_scrSettings_contTopBar2= NULL;
ui_scrSettings_lblSettings= NULL;
ui_scrSettings_btnBack= NULL;
ui_scrSettings_cntDatetime= NULL;
ui_scrSettings_iconDatetime= NULL;
ui_scrSettings_lblDatetime= NULL;
ui_scrSettings_lblDatetimeBrief= NULL;
ui_scrSettings_iconDatetimeEnter= NULL;
ui_scrSettings_cntScreen= NULL;
ui_scrSettings_iconScreen= NULL;
ui_scrSettings_lblScreen= NULL;
ui_scrSettings_lblScreenBrief= NULL;
ui_scrSettings_iconScreenEnter= NULL;
ui_scrSettings_cntMeasure= NULL;
ui_scrSettings_iconMeasure= NULL;
ui_scrSettings_lblMeasure= NULL;
ui_scrSettings_lblMeasureBrief= NULL;
ui_scrSettings_iconMeasureEnter= NULL;
ui_scrSettings_cntInfo= NULL;
ui_scrSettings_iconInfo= NULL;
ui_scrSettings_lblInfo= NULL;
ui_scrSettings_lblInfoBrief= NULL;
ui_scrSettings_iconInfoEnter= NULL;

}
