// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRMENU_H
#define UI_SCRMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMenu
extern void ui_scrMenu_screen_init(void);
extern void ui_scrMenu_screen_destroy(void);
extern void ui_event_scrMenu( lv_event_t * e);
extern lv_obj_t *ui_scrMenu;
extern lv_obj_t *ui_scrMenu_contTopBar;
extern lv_obj_t *ui_scrMenu_btnMenuPlotter;
extern void ui_event_scrMenu_btnMenuFFT( lv_event_t * e);
extern lv_obj_t *ui_scrMenu_btnMenuFFT;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

