// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRDATETIME_H
#define UI_SCRDATETIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrDatetime
extern void ui_scrDatetime_screen_init(void);
extern void ui_scrDatetime_screen_destroy(void);
extern lv_obj_t *ui_scrDatetime;
extern lv_obj_t *ui_scrDatetime_contTopBar3;
extern lv_obj_t *ui_scrDatetime_lblDatime;
extern void ui_event_scrDatetime_btnBack( lv_event_t * e);
extern lv_obj_t *ui_scrDatetime_btnBack;
extern lv_obj_t *ui_scrDatetime_lblDate;
extern lv_obj_t *ui_scrDatetime_cntDay;
extern lv_obj_t *ui_scrDatetime_dayUp;
extern lv_obj_t *ui_scrDatetime_lblDayV;
extern lv_obj_t *ui_scrDatetime_dayDown;
extern lv_obj_t *ui_scrDatetime_lblDay;
extern lv_obj_t *ui_scrDatetime_cntMonth;
extern lv_obj_t *ui_scrDatetime_monthUp;
extern lv_obj_t *ui_scrDatetime_lblMonthV;
extern lv_obj_t *ui_scrDatetime_monthDown;
extern lv_obj_t *ui_scrDatetime_lblMonth;
extern lv_obj_t *ui_scrDatetime_cntYear;
extern lv_obj_t *ui_scrDatetime_yearUp;
extern lv_obj_t *ui_scrDatetime_lblYearV;
extern lv_obj_t *ui_scrDatetime_yearDown;
extern lv_obj_t *ui_scrDatetime_lblYear;
extern lv_obj_t *ui_scrDatetime_vline;
extern lv_obj_t *ui_scrDatetime_lblTime;
extern lv_obj_t *ui_scrDatetime_cntHour;
extern lv_obj_t *ui_scrDatetime_hourUp;
extern lv_obj_t *ui_scrDatetime_lblHourV;
extern lv_obj_t *ui_scrDatetime_hourDown;
extern lv_obj_t *ui_scrDatetime_lblHour;
extern lv_obj_t *ui_scrDatetime_cntMin;
extern lv_obj_t *ui_scrDatetime_minUp;
extern lv_obj_t *ui_scrDatetime_lblMinV;
extern lv_obj_t *ui_scrDatetime_minDown;
extern lv_obj_t *ui_scrDatetime_lblMin;
extern lv_obj_t *ui_scrDatetime_btnSave;
extern lv_obj_t *ui_scrDatetime_iconSave;
extern lv_obj_t *ui_scrDatetime_lblSave;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

