// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRFFT_H
#define UI_SCRFFT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrFFT
extern void ui_scrFFT_screen_init(void);
extern void ui_scrFFT_screen_destroy(void);
extern lv_obj_t *ui_scrFFT;
extern lv_obj_t *ui_scrFFT_contTopBar1;
extern lv_obj_t *ui_scrFFT_lblTitle;
extern lv_obj_t *ui_scrFFT_cntTension;
extern lv_obj_t *ui_scrFFT_legendVoltage;
extern lv_obj_t *ui_scrFFT_lblTension;
extern lv_obj_t *ui_scrFFT_cntCorriente;
extern lv_obj_t *ui_scrFFT_legendCorriente;
extern lv_obj_t *ui_scrFFT_lblCorriente;
extern lv_obj_t *ui_scrFFT_cntValues;
extern lv_obj_t *ui_scrFFT_cntFrequency;
extern lv_obj_t *ui_scrFFT_lblFrequency;
extern lv_obj_t *ui_scrFFT_lblFrequencyValue;
extern lv_obj_t *ui_scrFFT_lblFrequencyUnit;
extern lv_obj_t *ui_scrFFT_cntPeak;
extern lv_obj_t *ui_scrFFT_lblPeak;
extern lv_obj_t *ui_scrFFT_lblPeakValue;
extern lv_obj_t *ui_scrFFT_lblPeakUnit;
extern lv_obj_t *ui_scrFFT_cntRMS;
extern lv_obj_t *ui_scrFFT_lblRMS;
extern lv_obj_t *ui_scrFFT_lblRmsValue;
extern lv_obj_t *ui_scrFFT_lblRmsUnit;
extern lv_obj_t *ui_scrFFT_cntThdDiv;
extern lv_obj_t *ui_scrFFT_lblThdDiv;
extern lv_obj_t *ui_scrFFT_lblThdValue;
extern lv_obj_t *ui_scrFFT_lblThdUnit;
extern lv_obj_t *ui_scrFFT_chartView;
extern lv_obj_t *ui_scrFFT_chartView_Xaxis;
extern lv_obj_t *ui_scrFFT_chartView_Yaxis1;
extern lv_obj_t *ui_scrFFT_chartView_Yaxis2;
extern lv_obj_t *ui_scrFFT_lineH4;
extern lv_obj_t *ui_scrFFT_lineH5;
extern lv_obj_t *ui_scrFFT_lineH6;
extern lv_obj_t *ui_scrFFT_lineV9;
extern lv_obj_t *ui_scrFFT_lineV10;
extern lv_obj_t *ui_scrFFT_lineV11;
extern lv_obj_t *ui_scrFFT_lineV12;
extern lv_obj_t *ui_scrFFT_lineV13;
extern lv_obj_t *ui_scrFFT_lineV14;
extern lv_obj_t *ui_scrFFT_lineV15;
extern lv_obj_t *ui_scrFFT_lineV16;
extern lv_obj_t *ui_scrFFT_cntYLabels;
extern lv_obj_t *ui_scrFFT_lblUnit;
extern lv_obj_t *ui_scrFFT_lblTop;
extern lv_obj_t *ui_scrFFT_lblBot;
extern lv_obj_t *ui_scrFFT_cntSideMenu;
extern lv_obj_t *ui_scrFFT_cntMainSideMenu;
extern lv_obj_t *ui_scrFFT_lblOptions;
extern lv_obj_t *ui_scrFFT_lblSenal;
extern lv_obj_t *ui_scrFFT_cntSigVoltage;
extern lv_obj_t *ui_scrFFT_dotSigVoltage;
extern lv_obj_t *ui_scrFFT_lblSigVoltage;
extern lv_obj_t *ui_scrFFT_cntSigCorriente;
extern lv_obj_t *ui_scrFFT_dotSigCorriente;
extern lv_obj_t *ui_scrFFT_lblSigCorriente;
extern lv_obj_t *ui_scrFFT_lineDivH3;
extern lv_obj_t *ui_scrFFT_cntScaleV;
extern lv_obj_t *ui_scrFFT_iconScaleV;
extern lv_obj_t *ui_scrFFT_lblScaleV;
extern lv_obj_t *ui_scrFFT_lblScaleVValue;
extern lv_obj_t *ui_scrFFT_iconScaleVEnter;
extern lv_obj_t *ui_scrFFT_cntScaleH;
extern lv_obj_t *ui_scrFFT_iconScaleH;
extern lv_obj_t *ui_scrFFT_lblScaleH;
extern lv_obj_t *ui_scrFFT_lblScaleHValue;
extern lv_obj_t *ui_scrFFT_iconScaleHEnter;
extern lv_obj_t *ui_scrFFT_lineDivH4;
extern void ui_event_scrFFT_cntBack( lv_event_t * e);
extern lv_obj_t *ui_scrFFT_cntBack;
extern lv_obj_t *ui_scrFFT_iconBack;
extern lv_obj_t *ui_scrFFT_lblBack;
extern lv_obj_t *ui_scrFFT_cntScaleMenu;
extern lv_obj_t *ui_scrFFT_btnScaleBack;
extern lv_obj_t *ui_scrFFT_lblScaleMenu;
extern lv_obj_t *ui_scrFFT_lineScaleMenuH;
extern lv_obj_t *ui_scrFFT_cntScales;
extern lv_obj_t *ui_scrFFT_cntScale1;
extern lv_obj_t *ui_scrFFT_lblScale1;
extern lv_obj_t *ui_scrFFT_iconScale1Tick;
extern lv_obj_t *ui_scrFFT_cntScale2;
extern lv_obj_t *ui_scrFFT_lblScale2;
extern lv_obj_t *ui_scrFFT_iconScale2Tick;
extern lv_obj_t *ui_scrFFT_cntScale3;
extern lv_obj_t *ui_scrFFT_lblScale3;
extern lv_obj_t *ui_scrFFT_iconScale3Tick;
extern lv_obj_t *ui_scrFFT_cntScale4;
extern lv_obj_t *ui_scrFFT_lblScale;
extern lv_obj_t *ui_scrFFT_iconScale4Tick;
extern lv_obj_t *ui_scrFFT_cntSpanMenu;
extern lv_obj_t *ui_scrFFT_btnSpanBack;
extern lv_obj_t *ui_scrFFT_lblSpanMenu;
extern lv_obj_t *ui_scrFFT_lineSpanMenuH;
extern lv_obj_t *ui_scrFFT_cntSpans;
extern lv_obj_t *ui_scrFFT_cntSpan1;
extern lv_obj_t *ui_scrFFT_lblSpan1;
extern lv_obj_t *ui_scrFFT_iconSpan1Tick;
extern lv_obj_t *ui_scrFFT_cntSpan2;
extern lv_obj_t *ui_scrFFT_lblSpan;
extern lv_obj_t *ui_scrFFT_iconSpan2Tick;
extern lv_obj_t *ui_scrFFT_cntSpan3;
extern lv_obj_t *ui_scrFFT_lblSpan3;
extern lv_obj_t *ui_scrFFT_iconSpan3Tick;
extern lv_obj_t *ui_scrFFT_cntSpan4;
extern lv_obj_t *ui_scrFFT_lblSpan4;
extern lv_obj_t *ui_scrFFT_iconSpan4Tick;
extern lv_obj_t *ui_scrFFT_cntSpan5;
extern lv_obj_t *ui_scrFFT_lblSpan5;
extern lv_obj_t *ui_scrFFT_iconSpan5Tick;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

