// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRFFT_H
#define UI_SCRFFT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrFFT
extern void ui_scrFFT_screen_init(void);
extern void ui_scrFFT_screen_destroy(void);
extern lv_obj_t *ui_scrFFT;
extern lv_obj_t *ui_scrFFT_contTopBar;
extern lv_obj_t *ui_scrFFT_chartFFT;
extern lv_obj_t *ui_scrFFT_chartFFT_Xaxis;
extern lv_obj_t *ui_scrFFT_chartFFT_Yaxis1;
extern lv_obj_t *ui_scrFFT_chartFFT_Yaxis2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

