// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Base[2] = {0x0D1117, 0x0D1117};
const ui_theme_variable_t _ui_theme_alpha_Base[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Panel[2] = {0x161B22, 0x161B22};
const ui_theme_variable_t _ui_theme_alpha_Panel[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Font_Primario[2] = {0xE6EDF3, 0xE6EDF3};
const ui_theme_variable_t _ui_theme_alpha_Font_Primario[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Font_Secundario[2] = {0x8B98A8, 0x8B98A8};
const ui_theme_variable_t _ui_theme_alpha_Font_Secundario[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Font_Atenuado[2] = {0x5B6675, 0x5B6675};
const ui_theme_variable_t _ui_theme_alpha_Font_Atenuado[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Foco[2] = {0x34D39E, 0x34D39E};
const ui_theme_variable_t _ui_theme_alpha_Foco[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Card[2] = {0x1C232D, 0x1C232D};
const ui_theme_variable_t _ui_theme_alpha_Card[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Card_Border[2] = {0x232D35, 0x232D35};
const ui_theme_variable_t _ui_theme_alpha_Card_Border[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Card_Focused[2] = {0x34D39E, 0x34D39E};
const ui_theme_variable_t _ui_theme_alpha_Card_Focused[2] = {36, 36};

const ui_theme_variable_t _ui_theme_color_Border_Focused[2] = {0x34D39E, 0x34D39E};
const ui_theme_variable_t _ui_theme_alpha_Border_Focused[2] = {140, 140};

const ui_theme_variable_t _ui_theme_color_Icon_Border[2] = {0x313B48, 0x313B48};
const ui_theme_variable_t _ui_theme_alpha_Icon_Border[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Icon_Bg[2] = {0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_Icon_Bg[2] = {8, 8};

const ui_theme_variable_t _ui_theme_color_Icon_Bg_Focused[2] = {0x34D39E, 0x34D39E};
const ui_theme_variable_t _ui_theme_alpha_Icon_Bg_Focused[2] = {41, 41};

const ui_theme_variable_t _ui_theme_color_Voltage[2] = {0xFFD23F, 0xFFD23F};
const ui_theme_variable_t _ui_theme_alpha_Voltage[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Corriente[2] = {0x33D6EE, 0x33D6EE};
const ui_theme_variable_t _ui_theme_alpha_Corriente[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DARK;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

