// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BASE 0
#define UI_THEME_COLOR_PANEL 1
#define UI_THEME_COLOR_FONT_PRIMARIO 2
#define UI_THEME_COLOR_FONT_SECUNDARIO 3
#define UI_THEME_COLOR_FONT_ATENUADO 4
#define UI_THEME_COLOR_FOCO 5
#define UI_THEME_COLOR_CARD 6
#define UI_THEME_COLOR_CARD_BORDER 7
#define UI_THEME_COLOR_CARD_FOCUSED 8
#define UI_THEME_COLOR_BORDER_FOCUSED 9
#define UI_THEME_COLOR_ICON_BORDER 10
#define UI_THEME_COLOR_ICON_BG 11
#define UI_THEME_COLOR_ICON_BG_FOCUSED 12
#define UI_THEME_COLOR_VOLTAGE 13
#define UI_THEME_COLOR_CORRIENTE 14

#define UI_THEME_DEFAULT 0

#define UI_THEME_DARK 1

extern const ui_theme_variable_t _ui_theme_color_Base[2];
extern const ui_theme_variable_t _ui_theme_alpha_Base[2];

extern const ui_theme_variable_t _ui_theme_color_Panel[2];
extern const ui_theme_variable_t _ui_theme_alpha_Panel[2];

extern const ui_theme_variable_t _ui_theme_color_Font_Primario[2];
extern const ui_theme_variable_t _ui_theme_alpha_Font_Primario[2];

extern const ui_theme_variable_t _ui_theme_color_Font_Secundario[2];
extern const ui_theme_variable_t _ui_theme_alpha_Font_Secundario[2];

extern const ui_theme_variable_t _ui_theme_color_Font_Atenuado[2];
extern const ui_theme_variable_t _ui_theme_alpha_Font_Atenuado[2];

extern const ui_theme_variable_t _ui_theme_color_Foco[2];
extern const ui_theme_variable_t _ui_theme_alpha_Foco[2];

extern const ui_theme_variable_t _ui_theme_color_Card[2];
extern const ui_theme_variable_t _ui_theme_alpha_Card[2];

extern const ui_theme_variable_t _ui_theme_color_Card_Border[2];
extern const ui_theme_variable_t _ui_theme_alpha_Card_Border[2];

extern const ui_theme_variable_t _ui_theme_color_Card_Focused[2];
extern const ui_theme_variable_t _ui_theme_alpha_Card_Focused[2];

extern const ui_theme_variable_t _ui_theme_color_Border_Focused[2];
extern const ui_theme_variable_t _ui_theme_alpha_Border_Focused[2];

extern const ui_theme_variable_t _ui_theme_color_Icon_Border[2];
extern const ui_theme_variable_t _ui_theme_alpha_Icon_Border[2];

extern const ui_theme_variable_t _ui_theme_color_Icon_Bg[2];
extern const ui_theme_variable_t _ui_theme_alpha_Icon_Bg[2];

extern const ui_theme_variable_t _ui_theme_color_Icon_Bg_Focused[2];
extern const ui_theme_variable_t _ui_theme_alpha_Icon_Bg_Focused[2];

extern const ui_theme_variable_t _ui_theme_color_Voltage[2];
extern const ui_theme_variable_t _ui_theme_alpha_Voltage[2];

extern const ui_theme_variable_t _ui_theme_color_Corriente[2];
extern const ui_theme_variable_t _ui_theme_alpha_Corriente[2];

extern const uint32_t* ui_theme_colors[2];
extern const uint8_t* ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
