// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef _UI_COMP_CONTTOPBAR_H
#define _UI_COMP_CONTTOPBAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT contTopBar
#define UI_COMP_CONTTOPBAR_CONTTOPBAR 0
#define UI_COMP_CONTTOPBAR_CONTDATE 1
#define _UI_COMP_CONTTOPBAR_NUM 2
lv_obj_t *ui_contTopBar_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
