// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "../ui.h"

// COMPONENT contTopBar

lv_obj_t *ui_contTopBar_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_contTopBar;
cui_contTopBar = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_contTopBar);
lv_obj_set_width( cui_contTopBar, 480);
lv_obj_set_height( cui_contTopBar, 20);
lv_obj_remove_flag( cui_contTopBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_contTopBar, lv_color_hex(0xC1C9FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_contTopBar, 218, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_contDate;
cui_contDate = lv_label_create(cui_contTopBar);
lv_obj_set_width( cui_contDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_contDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_contDate, -10 );
lv_obj_set_y( cui_contDate, 0 );
lv_obj_set_align( cui_contDate, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_contDate,"Lun 11 May 12:23 PM");
lv_obj_set_style_text_color(cui_contDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_contDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_contDate, &ui_font_poppinsReg10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTTOPBAR_NUM);
children[UI_COMP_CONTTOPBAR_CONTTOPBAR] = cui_contTopBar;
children[UI_COMP_CONTTOPBAR_CONTDATE] = cui_contDate;
lv_obj_add_event_cb(cui_contTopBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_contTopBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_contTopBar_create_hook(cui_contTopBar);
return cui_contTopBar; 
}

