// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCROSCILLOSCOPE_H
#define UI_SCROSCILLOSCOPE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrOscilloscope
extern void ui_scrOscilloscope_screen_init(void);
extern void ui_scrOscilloscope_screen_destroy(void);
extern lv_obj_t *ui_scrOscilloscope;
extern lv_obj_t *ui_scrOscilloscope_contTopBar;
extern lv_obj_t *ui_scrOscilloscope_lblTitle;
extern lv_obj_t *ui_scrOscilloscope_cntTension;
extern lv_obj_t *ui_scrOscilloscope_legendVoltage;
extern lv_obj_t *ui_scrOscilloscope_lblTension;
extern lv_obj_t *ui_scrOscilloscope_cntCorriente;
extern lv_obj_t *ui_scrOscilloscope_legendCorriente;
extern lv_obj_t *ui_scrOscilloscope_lblCorriente;
extern lv_obj_t *ui_scrOscilloscope_cntValues;
extern lv_obj_t *ui_scrOscilloscope_cntPeak;
extern lv_obj_t *ui_scrOscilloscope_lblPeak;
extern lv_obj_t *ui_scrOscilloscope_lblPeakValue;
extern lv_obj_t *ui_scrOscilloscope_lblPeakUnit;
extern lv_obj_t *ui_scrOscilloscope_cntRMS;
extern lv_obj_t *ui_scrOscilloscope_lblRMS;
extern lv_obj_t *ui_scrOscilloscope_lblRmsValue;
extern lv_obj_t *ui_scrOscilloscope_lblRmsUnit;
extern lv_obj_t *ui_scrOscilloscope_cntFrequency;
extern lv_obj_t *ui_scrOscilloscope_lblFrequency;
extern lv_obj_t *ui_scrOscilloscope_lblFrequencyValue;
extern lv_obj_t *ui_scrOscilloscope_lblFrequencyUnit;
extern lv_obj_t *ui_scrOscilloscope_cntTimeDiv;
extern lv_obj_t *ui_scrOscilloscope_lblTimeDiv;
extern lv_obj_t *ui_scrOscilloscope_lblTimeDivValue;
extern lv_obj_t *ui_scrOscilloscope_lblTimeDivValueUnit;
extern lv_obj_t *ui_scrOscilloscope_chartView;
extern lv_obj_t *ui_scrOscilloscope_chartView_Xaxis;
extern lv_obj_t *ui_scrOscilloscope_chartView_Yaxis1;
extern lv_obj_t *ui_scrOscilloscope_chartView_Yaxis2;
extern lv_obj_t *ui_scrOscilloscope_lineH1;
extern lv_obj_t *ui_scrOscilloscope_lineH2;
extern lv_obj_t *ui_scrOscilloscope_lineH3;
extern lv_obj_t *ui_scrOscilloscope_lineV1;
extern lv_obj_t *ui_scrOscilloscope_lineV2;
extern lv_obj_t *ui_scrOscilloscope_lineV3;
extern lv_obj_t *ui_scrOscilloscope_lineV4;
extern lv_obj_t *ui_scrOscilloscope_lineV5;
extern lv_obj_t *ui_scrOscilloscope_lineV6;
extern lv_obj_t *ui_scrOscilloscope_lineV7;
extern lv_obj_t *ui_scrOscilloscope_lineV8;
extern lv_obj_t *ui_scrOscilloscope_cntYLabels;
extern lv_obj_t *ui_scrOscilloscope_lblMiddle;
extern lv_obj_t *ui_scrOscilloscope_lblUnit;
extern lv_obj_t *ui_scrOscilloscope_lblTop;
extern lv_obj_t *ui_scrOscilloscope_lblBot;
extern lv_obj_t *ui_scrOscilloscope_cntSideMenu;
extern lv_obj_t *ui_scrOscilloscope_cntMainSideMenu;
extern lv_obj_t *ui_scrOscilloscope_lblOptions;
extern lv_obj_t *ui_scrOscilloscope_lblSenal;
extern lv_obj_t *ui_scrOscilloscope_cntSigVoltage;
extern lv_obj_t *ui_scrOscilloscope_dotSigVoltage;
extern lv_obj_t *ui_scrOscilloscope_lblSigVoltage;
extern lv_obj_t *ui_scrOscilloscope_cntSigCorriente;
extern lv_obj_t *ui_scrOscilloscope_dotSigCorriente;
extern lv_obj_t *ui_scrOscilloscope_lblSigCorriente;
extern lv_obj_t *ui_scrOscilloscope_lineDivH1;
extern lv_obj_t *ui_scrOscilloscope_cntScaleV;
extern lv_obj_t *ui_scrOscilloscope_iconScaleV;
extern lv_obj_t *ui_scrOscilloscope_lblScaleV;
extern lv_obj_t *ui_scrOscilloscope_lblScaleVValue;
extern lv_obj_t *ui_scrOscilloscope_iconScaleVEnter;
extern lv_obj_t *ui_scrOscilloscope_cntScaleH;
extern lv_obj_t *ui_scrOscilloscope_iconScaleH;
extern lv_obj_t *ui_scrOscilloscope_lblScaleH;
extern lv_obj_t *ui_scrOscilloscope_lblScaleHValue;
extern lv_obj_t *ui_scrOscilloscope_iconScaleHEnter;
extern lv_obj_t *ui_scrOscilloscope_lineDivH2;
extern void ui_event_scrOscilloscope_cntBack( lv_event_t * e);
extern lv_obj_t *ui_scrOscilloscope_cntBack;
extern lv_obj_t *ui_scrOscilloscope_iconBack;
extern lv_obj_t *ui_scrOscilloscope_lblBack;
extern lv_obj_t *ui_scrOscilloscope_cntScaleMenu;
extern lv_obj_t *ui_scrOscilloscope_btnScaleBack;
extern lv_obj_t *ui_scrOscilloscope_lblScaleMenu;
extern lv_obj_t *ui_scrOscilloscope_lineScaleMenuH;
extern lv_obj_t *ui_scrOscilloscope_cntScales;
extern lv_obj_t *ui_scrOscilloscope_cntScale1;
extern lv_obj_t *ui_scrOscilloscope_lblScale1;
extern lv_obj_t *ui_scrOscilloscope_iconScale1Tick;
extern lv_obj_t *ui_scrOscilloscope_cntScale2;
extern lv_obj_t *ui_scrOscilloscope_lblScale2;
extern lv_obj_t *ui_scrOscilloscope_iconScale2Tick;
extern lv_obj_t *ui_scrOscilloscope_cntScale3;
extern lv_obj_t *ui_scrOscilloscope_lblScale3;
extern lv_obj_t *ui_scrOscilloscope_iconScale3Tick;
extern lv_obj_t *ui_scrOscilloscope_cntScale4;
extern lv_obj_t *ui_scrOscilloscope_lblScale4;
extern lv_obj_t *ui_scrOscilloscope_iconScale4Tick;
extern lv_obj_t *ui_scrOscilloscope_cntTimeMenu;
extern lv_obj_t *ui_scrOscilloscope_btnTimeBack;
extern lv_obj_t *ui_scrOscilloscope_lblTimeMenu;
extern lv_obj_t *ui_scrOscilloscope_lineTimeMenuH;
extern lv_obj_t *ui_scrOscilloscope_cntTimes;
extern lv_obj_t *ui_scrOscilloscope_cntTime1;
extern lv_obj_t *ui_scrOscilloscope_lblTime1;
extern lv_obj_t *ui_scrOscilloscope_iconTime1Tick;
extern lv_obj_t *ui_scrOscilloscope_cntTime2;
extern lv_obj_t *ui_scrOscilloscope_lblTime2;
extern lv_obj_t *ui_scrOscilloscope_iconTime2Tick;
extern lv_obj_t *ui_scrOscilloscope_cntTime3;
extern lv_obj_t *ui_scrOscilloscope_lblTime3;
extern lv_obj_t *ui_scrOscilloscope_iconTime3Tick;
extern lv_obj_t *ui_scrOscilloscope_cntTime4;
extern lv_obj_t *ui_scrOscilloscope_lblTime4;
extern lv_obj_t *ui_scrOscilloscope_iconTime4Tick;
extern lv_obj_t *ui_scrOscilloscope_cntTime5;
extern lv_obj_t *ui_scrOscilloscope_lblTime5;
extern lv_obj_t *ui_scrOscilloscope_iconTime5Tick;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

