// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#include "../ui.h"

lv_obj_t *ui_scrTimeout = NULL;lv_obj_t *ui_scrTimeout_contTopBar = NULL;lv_obj_t *ui_scrTimeout_lblScreen = NULL;lv_obj_t *ui_scrTimeout_btnBack = NULL;lv_obj_t *ui_scrTimeout_iconScreen = NULL;lv_obj_t *ui_scrTimeout_lblScreenOff = NULL;lv_obj_t *ui_scrTimeout_lblScreenOffInfo = NULL;lv_obj_t *ui_scrTimeout_btnScreenOff30s = NULL;lv_obj_t *ui_scrTimeout_lblOff30s = NULL;lv_obj_t *ui_scrTimeout_btnScreenOff1m = NULL;lv_obj_t *ui_scrTimeout_lblOff1m = NULL;lv_obj_t *ui_scrTimeout_btnScreenOff2m = NULL;lv_obj_t *ui_scrTimeout_lblOff2m = NULL;lv_obj_t *ui_scrTimeout_btnScreenOff5m = NULL;lv_obj_t *ui_scrTimeout_lblOff5m = NULL;lv_obj_t *ui_scrTimeout_btnScreenOff10m = NULL;lv_obj_t *ui_scrTimeout_lblOff10m = NULL;lv_obj_t *ui_scrTimeout_btnScreenOffNever = NULL;lv_obj_t *ui_scrTimeout_lblOffNever = NULL;lv_obj_t *ui_scrTimeout_vline = NULL;lv_obj_t *ui_scrTimeout_iconBack = NULL;lv_obj_t *ui_scrTimeout_lblScreenBack = NULL;lv_obj_t *ui_scrTimeout_lblScreenBackInfo = NULL;lv_obj_t *ui_scrTimeout_btnScreenBack30s = NULL;lv_obj_t *ui_scrTimeout_lblOff30s1 = NULL;lv_obj_t *ui_scrTimeout_btnScreenBack1m = NULL;lv_obj_t *ui_scrTimeout_lblOff1m1 = NULL;lv_obj_t *ui_scrTimeout_btnScreenBack2m = NULL;lv_obj_t *ui_scrTimeout_lblOff2m1 = NULL;lv_obj_t *ui_scrTimeout_btnScreenBack5m = NULL;lv_obj_t *ui_scrTimeout_lblOff5m1 = NULL;lv_obj_t *ui_scrTimeout_btnScreenBack10m = NULL;lv_obj_t *ui_scrTimeout_lblOff10m1 = NULL;lv_obj_t *ui_scrTimeout_btnScreenBackNever = NULL;lv_obj_t *ui_scrTimeout_lblOffNever1 = NULL;
// event funtions
void ui_event_scrTimeout_btnBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_scrSettings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_scrSettings_screen_init);
}
}

// build funtions

void ui_scrTimeout_screen_init(void)
{
ui_scrTimeout = lv_obj_create(NULL);
lv_obj_remove_flag( ui_scrTimeout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_scrTimeout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);

ui_scrTimeout_contTopBar = ui_contTopBar_create(ui_scrTimeout);
lv_obj_set_x( ui_scrTimeout_contTopBar, 0 );
lv_obj_set_y( ui_scrTimeout_contTopBar, 0 );

ui_scrTimeout_lblScreen = lv_label_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_lblScreen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblScreen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrTimeout_lblScreen, 52 );
lv_obj_set_y( ui_scrTimeout_lblScreen, 41 );
lv_label_set_text(ui_scrTimeout_lblScreen,"Pantalla");
ui_object_set_themeable_style_property(ui_scrTimeout_lblScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrTimeout_lblScreen, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrTimeout_lblScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrTimeout_lblScreen, &ui_font_SansBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrTimeout_btnBack = lv_image_create(ui_scrTimeout);
lv_image_set_src(ui_scrTimeout_btnBack, &ui_img_icons_ic_back_png);
lv_obj_set_width( ui_scrTimeout_btnBack, 28);
lv_obj_set_height( ui_scrTimeout_btnBack, 28);
lv_obj_set_x( ui_scrTimeout_btnBack, 14 );
lv_obj_set_y( ui_scrTimeout_btnBack, 37 );
lv_obj_add_flag( ui_scrTimeout_btnBack, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrTimeout_btnBack,85);
lv_obj_set_style_radius(ui_scrTimeout_btnBack, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Card);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Card);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnBack, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnBack, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_Foco);

ui_scrTimeout_iconScreen = lv_image_create(ui_scrTimeout);
lv_image_set_src(ui_scrTimeout_iconScreen, &ui_img_icons_ic_screen_png);
lv_obj_set_width( ui_scrTimeout_iconScreen, 16);
lv_obj_set_height( ui_scrTimeout_iconScreen, 16);
lv_obj_set_x( ui_scrTimeout_iconScreen, 16 );
lv_obj_set_y( ui_scrTimeout_iconScreen, 83 );
lv_obj_add_flag( ui_scrTimeout_iconScreen, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_iconScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrTimeout_iconScreen,85);

ui_scrTimeout_lblScreenOff = lv_label_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_lblScreenOff, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblScreenOff, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrTimeout_lblScreenOff, 40 );
lv_obj_set_y( ui_scrTimeout_lblScreenOff, 82 );
lv_label_set_text(ui_scrTimeout_lblScreenOff,"Apagado de pantalla");
ui_object_set_themeable_style_property(ui_scrTimeout_lblScreenOff, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblScreenOff, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrTimeout_lblScreenOff, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrTimeout_lblScreenOff, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrTimeout_lblScreenOff, &ui_font_SansBold13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrTimeout_lblScreenOffInfo = lv_label_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_lblScreenOffInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblScreenOffInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrTimeout_lblScreenOffInfo, 16 );
lv_obj_set_y( ui_scrTimeout_lblScreenOffInfo, 103 );
lv_label_set_text(ui_scrTimeout_lblScreenOffInfo,"Apaga el retroiluminado tras inactividad.");
ui_object_set_themeable_style_property(ui_scrTimeout_lblScreenOffInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrTimeout_lblScreenOffInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_font(ui_scrTimeout_lblScreenOffInfo, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrTimeout_btnScreenOff30s = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenOff30s, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenOff30s, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenOff30s, 16 );
lv_obj_set_y( ui_scrTimeout_btnScreenOff30s, 129 );
lv_obj_add_flag( ui_scrTimeout_btnScreenOff30s, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenOff30s, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenOff30s, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenOff30s, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenOff30s, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenOff30s, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenOff30s, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenOff30s, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenOff30s, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenOff30s, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff30s, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOff30s, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOff30s, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOff30s, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOff30s, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOff30s = lv_label_create(ui_scrTimeout_btnScreenOff30s);
lv_obj_set_width( ui_scrTimeout_lblOff30s, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOff30s, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOff30s, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOff30s,"30s");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOff30s, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

ui_scrTimeout_btnScreenOff1m = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenOff1m, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenOff1m, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenOff1m, 87 );
lv_obj_set_y( ui_scrTimeout_btnScreenOff1m, 129 );
lv_obj_add_flag( ui_scrTimeout_btnScreenOff1m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenOff1m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenOff1m, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenOff1m, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenOff1m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenOff1m, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenOff1m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenOff1m, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenOff1m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenOff1m, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff1m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOff1m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOff1m, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOff1m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOff1m, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOff1m = lv_label_create(ui_scrTimeout_btnScreenOff1m);
lv_obj_set_width( ui_scrTimeout_lblOff1m, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOff1m, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOff1m, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOff1m,"1m");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOff1m, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

ui_scrTimeout_btnScreenOff2m = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenOff2m, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenOff2m, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenOff2m, 157 );
lv_obj_set_y( ui_scrTimeout_btnScreenOff2m, 129 );
lv_obj_add_flag( ui_scrTimeout_btnScreenOff2m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenOff2m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenOff2m, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenOff2m, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenOff2m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenOff2m, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenOff2m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenOff2m, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenOff2m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenOff2m, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff2m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOff2m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOff2m, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOff2m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOff2m, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOff2m = lv_label_create(ui_scrTimeout_btnScreenOff2m);
lv_obj_set_width( ui_scrTimeout_lblOff2m, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOff2m, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOff2m, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOff2m,"2m");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOff2m, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

ui_scrTimeout_btnScreenOff5m = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenOff5m, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenOff5m, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenOff5m, 16 );
lv_obj_set_y( ui_scrTimeout_btnScreenOff5m, 167 );
lv_obj_add_flag( ui_scrTimeout_btnScreenOff5m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenOff5m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenOff5m, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenOff5m, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenOff5m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenOff5m, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenOff5m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenOff5m, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenOff5m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenOff5m, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff5m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOff5m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOff5m, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOff5m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOff5m, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOff5m = lv_label_create(ui_scrTimeout_btnScreenOff5m);
lv_obj_set_width( ui_scrTimeout_lblOff5m, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOff5m, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOff5m, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOff5m,"5m");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOff5m, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

ui_scrTimeout_btnScreenOff10m = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenOff10m, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenOff10m, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenOff10m, 87 );
lv_obj_set_y( ui_scrTimeout_btnScreenOff10m, 167 );
lv_obj_add_flag( ui_scrTimeout_btnScreenOff10m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenOff10m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenOff10m, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenOff10m, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenOff10m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenOff10m, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenOff10m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenOff10m, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenOff10m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenOff10m, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOff10m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOff10m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOff10m, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOff10m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOff10m, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOff10m = lv_label_create(ui_scrTimeout_btnScreenOff10m);
lv_obj_set_width( ui_scrTimeout_lblOff10m, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOff10m, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOff10m, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOff10m,"10m");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOff10m, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

ui_scrTimeout_btnScreenOffNever = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenOffNever, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenOffNever, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenOffNever, 157 );
lv_obj_set_y( ui_scrTimeout_btnScreenOffNever, 167 );
lv_obj_add_flag( ui_scrTimeout_btnScreenOffNever, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenOffNever, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenOffNever, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenOffNever, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenOffNever, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenOffNever, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenOffNever, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenOffNever, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenOffNever, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenOffNever, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenOffNever, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOffNever, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOffNever, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenOffNever, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenOffNever, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOffNever = lv_label_create(ui_scrTimeout_btnScreenOffNever);
lv_obj_set_width( ui_scrTimeout_lblOffNever, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOffNever, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOffNever, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOffNever,"Nunca");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOffNever, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

ui_scrTimeout_vline = lv_label_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_vline, 1);
lv_obj_set_height( ui_scrTimeout_vline, 115);
lv_obj_set_x( ui_scrTimeout_vline, 240 );
lv_obj_set_y( ui_scrTimeout_vline, 82 );
lv_label_set_text(ui_scrTimeout_vline,"");
ui_object_set_themeable_style_property(ui_scrTimeout_vline, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrTimeout_vline, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_border_width(ui_scrTimeout_vline, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrTimeout_iconBack = lv_image_create(ui_scrTimeout);
lv_image_set_src(ui_scrTimeout_iconBack, &ui_img_icons_ic_back_png);
lv_obj_set_width( ui_scrTimeout_iconBack, 16);
lv_obj_set_height( ui_scrTimeout_iconBack, 16);
lv_obj_set_x( ui_scrTimeout_iconBack, 259 );
lv_obj_set_y( ui_scrTimeout_iconBack, 83 );
lv_obj_add_flag( ui_scrTimeout_iconBack, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_iconBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_scrTimeout_iconBack,85);

ui_scrTimeout_lblScreenBack = lv_label_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_lblScreenBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblScreenBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrTimeout_lblScreenBack, 283 );
lv_obj_set_y( ui_scrTimeout_lblScreenBack, 82 );
lv_label_set_text(ui_scrTimeout_lblScreenBack,"Volver al menú");
ui_object_set_themeable_style_property(ui_scrTimeout_lblScreenBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Primario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblScreenBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Primario);
lv_obj_set_style_text_letter_space(ui_scrTimeout_lblScreenBack, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_scrTimeout_lblScreenBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_scrTimeout_lblScreenBack, &ui_font_SansBold13, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrTimeout_lblScreenBackInfo = lv_label_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_lblScreenBackInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblScreenBackInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_scrTimeout_lblScreenBackInfo, 259 );
lv_obj_set_y( ui_scrTimeout_lblScreenBackInfo, 103 );
lv_label_set_text(ui_scrTimeout_lblScreenBackInfo,"Regresa al menú principal tras inactividad.");
ui_object_set_themeable_style_property(ui_scrTimeout_lblScreenBackInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Atenuado);
ui_object_set_themeable_style_property(ui_scrTimeout_lblScreenBackInfo, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Atenuado);
lv_obj_set_style_text_font(ui_scrTimeout_lblScreenBackInfo, &ui_font_SansReg10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrTimeout_btnScreenBack30s = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenBack30s, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenBack30s, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenBack30s, 259 );
lv_obj_set_y( ui_scrTimeout_btnScreenBack30s, 129 );
lv_obj_add_flag( ui_scrTimeout_btnScreenBack30s, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenBack30s, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenBack30s, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenBack30s, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenBack30s, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenBack30s, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenBack30s, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenBack30s, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenBack30s, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenBack30s, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack30s, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBack30s, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBack30s, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBack30s, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBack30s, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOff30s1 = lv_label_create(ui_scrTimeout_btnScreenBack30s);
lv_obj_set_width( ui_scrTimeout_lblOff30s1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOff30s1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOff30s1, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOff30s1,"30s");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOff30s1, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff30s1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

ui_scrTimeout_btnScreenBack1m = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenBack1m, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenBack1m, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenBack1m, 329 );
lv_obj_set_y( ui_scrTimeout_btnScreenBack1m, 129 );
lv_obj_add_flag( ui_scrTimeout_btnScreenBack1m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenBack1m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenBack1m, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenBack1m, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenBack1m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenBack1m, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenBack1m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenBack1m, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenBack1m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenBack1m, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack1m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBack1m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBack1m, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBack1m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBack1m, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOff1m1 = lv_label_create(ui_scrTimeout_btnScreenBack1m);
lv_obj_set_width( ui_scrTimeout_lblOff1m1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOff1m1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOff1m1, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOff1m1,"1m");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOff1m1, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff1m1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

ui_scrTimeout_btnScreenBack2m = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenBack2m, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenBack2m, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenBack2m, 400 );
lv_obj_set_y( ui_scrTimeout_btnScreenBack2m, 129 );
lv_obj_add_flag( ui_scrTimeout_btnScreenBack2m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenBack2m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenBack2m, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenBack2m, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenBack2m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenBack2m, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenBack2m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenBack2m, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenBack2m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenBack2m, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack2m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBack2m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBack2m, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBack2m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBack2m, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOff2m1 = lv_label_create(ui_scrTimeout_btnScreenBack2m);
lv_obj_set_width( ui_scrTimeout_lblOff2m1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOff2m1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOff2m1, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOff2m1,"2m");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOff2m1, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff2m1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

ui_scrTimeout_btnScreenBack5m = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenBack5m, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenBack5m, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenBack5m, 259 );
lv_obj_set_y( ui_scrTimeout_btnScreenBack5m, 167 );
lv_obj_add_flag( ui_scrTimeout_btnScreenBack5m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenBack5m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenBack5m, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenBack5m, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenBack5m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenBack5m, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenBack5m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenBack5m, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenBack5m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenBack5m, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack5m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBack5m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBack5m, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBack5m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBack5m, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOff5m1 = lv_label_create(ui_scrTimeout_btnScreenBack5m);
lv_obj_set_width( ui_scrTimeout_lblOff5m1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOff5m1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOff5m1, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOff5m1,"5m");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOff5m1, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff5m1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

ui_scrTimeout_btnScreenBack10m = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenBack10m, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenBack10m, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenBack10m, 329 );
lv_obj_set_y( ui_scrTimeout_btnScreenBack10m, 167 );
lv_obj_add_flag( ui_scrTimeout_btnScreenBack10m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenBack10m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenBack10m, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenBack10m, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenBack10m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenBack10m, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenBack10m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenBack10m, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenBack10m, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenBack10m, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBack10m, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBack10m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBack10m, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBack10m, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBack10m, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOff10m1 = lv_label_create(ui_scrTimeout_btnScreenBack10m);
lv_obj_set_width( ui_scrTimeout_lblOff10m1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOff10m1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOff10m1, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOff10m1,"10m");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOff10m1, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOff10m1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

ui_scrTimeout_btnScreenBackNever = lv_button_create(ui_scrTimeout);
lv_obj_set_width( ui_scrTimeout_btnScreenBackNever, 65);
lv_obj_set_height( ui_scrTimeout_btnScreenBackNever, 31);
lv_obj_set_x( ui_scrTimeout_btnScreenBackNever, 400 );
lv_obj_set_y( ui_scrTimeout_btnScreenBackNever, 167 );
lv_obj_add_flag( ui_scrTimeout_btnScreenBackNever, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_scrTimeout_btnScreenBackNever, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_scrTimeout_btnScreenBackNever, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Border);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Border);
lv_obj_set_style_border_width(ui_scrTimeout_btnScreenBackNever, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_scrTimeout_btnScreenBackNever, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_scrTimeout_btnScreenBackNever, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Foco);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Foco);
lv_obj_set_style_min_width(ui_scrTimeout_btnScreenBackNever, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_width(ui_scrTimeout_btnScreenBackNever, 65, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_min_height(ui_scrTimeout_btnScreenBackNever, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_max_height(ui_scrTimeout_btnScreenBackNever, 31, LV_PART_MAIN| LV_STATE_PRESSED);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_Card_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_btnScreenBackNever, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Card_Focused);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBackNever, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBackNever, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_scrTimeout_btnScreenBackNever, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_scrTimeout_btnScreenBackNever, 0, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_scrTimeout_lblOffNever1 = lv_label_create(ui_scrTimeout_btnScreenBackNever);
lv_obj_set_width( ui_scrTimeout_lblOffNever1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scrTimeout_lblOffNever1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scrTimeout_lblOffNever1, LV_ALIGN_CENTER );
lv_label_set_text(ui_scrTimeout_lblOffNever1,"Nunca");
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Font_Secundario);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Font_Secundario);
lv_obj_set_style_text_font(ui_scrTimeout_lblOffNever1, &ui_font_MonoBold11, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Base);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR, _ui_theme_color_Border_Focused);
ui_object_set_themeable_style_property(ui_scrTimeout_lblOffNever1, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Border_Focused);

lv_obj_add_event_cb(ui_scrTimeout_btnBack, ui_event_scrTimeout_btnBack, LV_EVENT_ALL, NULL);

}

void ui_scrTimeout_screen_destroy(void)
{
   if (ui_scrTimeout) lv_obj_del(ui_scrTimeout);

// NULL screen variables
ui_scrTimeout= NULL;
ui_scrTimeout_contTopBar= NULL;
ui_scrTimeout_lblScreen= NULL;
ui_scrTimeout_btnBack= NULL;
ui_scrTimeout_iconScreen= NULL;
ui_scrTimeout_lblScreenOff= NULL;
ui_scrTimeout_lblScreenOffInfo= NULL;
ui_scrTimeout_btnScreenOff30s= NULL;
ui_scrTimeout_lblOff30s= NULL;
ui_scrTimeout_btnScreenOff1m= NULL;
ui_scrTimeout_lblOff1m= NULL;
ui_scrTimeout_btnScreenOff2m= NULL;
ui_scrTimeout_lblOff2m= NULL;
ui_scrTimeout_btnScreenOff5m= NULL;
ui_scrTimeout_lblOff5m= NULL;
ui_scrTimeout_btnScreenOff10m= NULL;
ui_scrTimeout_lblOff10m= NULL;
ui_scrTimeout_btnScreenOffNever= NULL;
ui_scrTimeout_lblOffNever= NULL;
ui_scrTimeout_vline= NULL;
ui_scrTimeout_iconBack= NULL;
ui_scrTimeout_lblScreenBack= NULL;
ui_scrTimeout_lblScreenBackInfo= NULL;
ui_scrTimeout_btnScreenBack30s= NULL;
ui_scrTimeout_lblOff30s1= NULL;
ui_scrTimeout_btnScreenBack1m= NULL;
ui_scrTimeout_lblOff1m1= NULL;
ui_scrTimeout_btnScreenBack2m= NULL;
ui_scrTimeout_lblOff2m1= NULL;
ui_scrTimeout_btnScreenBack5m= NULL;
ui_scrTimeout_lblOff5m1= NULL;
ui_scrTimeout_btnScreenBack10m= NULL;
ui_scrTimeout_lblOff10m1= NULL;
ui_scrTimeout_btnScreenBackNever= NULL;
ui_scrTimeout_lblOffNever1= NULL;

}
