// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRBOOT_H
#define UI_SCRBOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrBoot
extern void ui_scrBoot_screen_init(void);
extern void ui_scrBoot_screen_destroy(void);
extern lv_obj_t *ui_scrBoot;
extern lv_obj_t *ui_scrBoot_lblTitle;
extern lv_obj_t *ui_scrBoot_spnrInit;
extern lv_obj_t *ui_scrBoot_imgLogo;
extern lv_obj_t *ui_scrBoot_lblInit;
extern lv_obj_t *ui_scrBoot_lblSubtitle;
extern lv_obj_t *ui_scrBoot_vLine;
extern lv_obj_t *ui_scrBoot_hLine;
extern lv_obj_t *ui_scrBoot_lblSn;
extern lv_obj_t *ui_scrBoot_lblSnV;
extern lv_obj_t *ui_scrBoot_lblFw;
extern lv_obj_t *ui_scrBoot_lblFwV;
extern lv_obj_t *ui_scrBoot_lblFacultyName;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

