// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRTIMEOUT_H
#define UI_SCRTIMEOUT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrTimeout
extern void ui_scrTimeout_screen_init(void);
extern void ui_scrTimeout_screen_destroy(void);
extern lv_obj_t *ui_scrTimeout;
extern lv_obj_t *ui_scrTimeout_contTopBar;
extern lv_obj_t *ui_scrTimeout_lblScreen;
extern void ui_event_scrTimeout_btnBack( lv_event_t * e);
extern lv_obj_t *ui_scrTimeout_btnBack;
extern lv_obj_t *ui_scrTimeout_iconScreen;
extern lv_obj_t *ui_scrTimeout_lblScreenOff;
extern lv_obj_t *ui_scrTimeout_lblScreenOffInfo;
extern lv_obj_t *ui_scrTimeout_btnScreenOff30s;
extern lv_obj_t *ui_scrTimeout_lblOff30s;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

