// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRINFORMATION_H
#define UI_SCRINFORMATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrInformation
extern void ui_scrInformation_screen_init(void);
extern void ui_scrInformation_screen_destroy(void);
extern lv_obj_t *ui_scrInformation;
extern lv_obj_t *ui_scrInformation_contTopBar;
extern lv_obj_t *ui_scrInformation_lblInfo;
extern void ui_event_scrInformation_btnBack( lv_event_t * e);
extern lv_obj_t *ui_scrInformation_btnBack;
extern lv_obj_t *ui_scrInformation_cntDevice;
extern lv_obj_t *ui_scrInformation_logo;
extern lv_obj_t *ui_scrInformation_lblName;
extern lv_obj_t *ui_scrInformation_lblSubname;
extern lv_obj_t *ui_scrInformation_cntModel;
extern lv_obj_t *ui_scrInformation_lblModel;
extern lv_obj_t *ui_scrInformation_lblModelV;
extern lv_obj_t *ui_scrInformation_cntSerial;
extern lv_obj_t *ui_scrInformation_lblSerial;
extern lv_obj_t *ui_scrInformation_lblSerialV;
extern lv_obj_t *ui_scrInformation_cntFirmware;
extern lv_obj_t *ui_scrInformation_lblFirmware;
extern lv_obj_t *ui_scrInformation_lblFirmwareV;
extern lv_obj_t *ui_scrInformation_cntBuild;
extern lv_obj_t *ui_scrInformation_lblBuild;
extern lv_obj_t *ui_scrInformation_lblBuildV;
extern lv_obj_t *ui_scrInformation_cntHardware;
extern lv_obj_t *ui_scrInformation_lblHardware;
extern lv_obj_t *ui_scrInformation_cntMcu;
extern lv_obj_t *ui_scrInformation_lblMcu;
extern lv_obj_t *ui_scrInformation_lblMcuV;
extern lv_obj_t *ui_scrInformation_cntAdc;
extern lv_obj_t *ui_scrInformation_lblAdc;
extern lv_obj_t *ui_scrInformation_lblAdcV;
extern lv_obj_t *ui_scrInformation_cntActiveTime;
extern lv_obj_t *ui_scrInformation_lblActiveTime;
extern lv_obj_t *ui_scrInformation_lblActiveTimeV;
extern lv_obj_t *ui_scrInformation_cntBy;
extern lv_obj_t *ui_scrInformation_lblBy;
extern lv_obj_t *ui_scrInformation_lblUniversity;
extern lv_obj_t *ui_scrInformation_lblProject;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

