// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ui

#ifndef UI_SCRMENU_H
#define UI_SCRMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMenu
extern void ui_scrMenu_screen_init(void);
extern void ui_scrMenu_screen_destroy(void);
extern lv_obj_t *ui_scrMenu;
extern lv_obj_t *ui_scrMenu_contTopBar;
extern lv_obj_t *ui_scrMenu_Label10;
extern void ui_event_scrMenu_cardOscilloscope( lv_event_t * e);
extern lv_obj_t *ui_scrMenu_cardOscilloscope;
extern lv_obj_t *ui_scrMenu_cardContRealTime;
extern lv_obj_t *ui_scrMenu_iconRealTime;
extern lv_obj_t *ui_scrMenu_lblRealTime;
extern lv_obj_t *ui_scrMenu_lblRealTimeInfo;
extern void ui_event_scrMenu_cardFFT( lv_event_t * e);
extern lv_obj_t *ui_scrMenu_cardFFT;
extern lv_obj_t *ui_scrMenu_cardContFft;
extern lv_obj_t *ui_scrMenu_iconFft;
extern lv_obj_t *ui_scrMenu_lblFft;
extern lv_obj_t *ui_scrMenu_lblFftInfo;
extern lv_obj_t *ui_scrMenu_cardMediciones;
extern lv_obj_t *ui_scrMenu_cardContMediciones;
extern lv_obj_t *ui_scrMenu_iconMediciones;
extern lv_obj_t *ui_scrMenu_lblMediciones;
extern lv_obj_t *ui_scrMenu_lblMedicionesInfo;
extern void ui_event_scrMenu_cardAjustes( lv_event_t * e);
extern lv_obj_t *ui_scrMenu_cardAjustes;
extern lv_obj_t *ui_scrMenu_cardContAjustes;
extern lv_obj_t *ui_scrMenu_iconAjustes;
extern lv_obj_t *ui_scrMenu_lblAjustes;
extern lv_obj_t *ui_scrMenu_lblAjustesInfo;
extern lv_obj_t *ui_scrMenu_cardRec;
extern lv_obj_t *ui_scrMenu_iconRec;
extern lv_obj_t *ui_scrMenu_lblRecord;
extern lv_obj_t *ui_scrMenu_cntBottomInfo;
extern lv_obj_t *ui_scrMenu_circle;
extern lv_obj_t *ui_scrMenu_lblBottomInfo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

